# Jupiter to automize clustering for Cats

In [2]:
import pandas as pd
import numpy as np
import sklearn.metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import autosklearn.classification

## Overture des données

In [3]:
df = pd.read_csv('data/OutCatdata.csv', na_filter= False)
df = df.drop("Unnamed: 0", axis= 1)

/tmp/ipykernel_95801/3855532020.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/OutCatdata.csv', na_filter= False)

/!\\ the NA values are dropped /!\\

## observation des données

In [3]:
df

,event.id,timestamp,location.long,location.lat,animal.id,animal.life.stage,animal.reproductive.condition,animal.sex,Hunt,N.pray,Hrs.indors,N.neigbours,StartDate,StartHours,EndDate,EndHours
0,6.331585e+08,2015-04-19 01:02:59.000,138.649719,-34.953682,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
1,6.331585e+08,2015-04-19 01:06:59.000,138.649429,-34.953598,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
2,6.331585e+08,2015-04-19 01:09:53.000,138.649429,-34.954014,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
3,6.331585e+08,2015-04-19 01:12:45.000,138.649765,-34.954140,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
4,6.331585e+08,2015-04-19 01:15:37.000,138.649368,-34.954044,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057315,2.412263e+09,2015-04-07 03:08:57.000,138.644196,-34.837971,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057316,2.412263e+09,2015-04-07 03:19:06.000,138.644257,-34.837906,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057317,2.412263e+09,2015-04-07 03:29:09.000,138.644531,-34.837643,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057318,2.412263e+09,2015-04-07 03:38:05.000,138.644089,-34.837967,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057319,2.412263e+09,2015-04-07 03:48:52.000,138.644073,-34.837761,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000

### division des jeux de données entre la classe à prédire (ici `Hunt`) et les autres variables

In [4]:
variables = df.drop(['Hunt'], axis = 1)
variables

,event.id,timestamp,location.long,location.lat,animal.id,animal.life.stage,animal.reproductive.condition,animal.sex,N.pray,Hrs.indors,N.neigbours,StartDate,StartHours,EndDate,EndHours
0,6.331585e+08,2015-04-19 01:02:59.000,138.649719,-34.953682,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
1,6.331585e+08,2015-04-19 01:06:59.000,138.649429,-34.953598,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
2,6.331585e+08,2015-04-19 01:09:53.000,138.649429,-34.954014,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
3,6.331585e+08,2015-04-19 01:12:45.000,138.649765,-34.954140,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
4,6.331585e+08,2015-04-19 01:15:37.000,138.649368,-34.954044,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057315,2.412263e+09,2015-04-07 03:08:57.000,138.644196,-34.837971,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057316,2.412263e+09,2015-04-07 03:19:06.000,138.644257,-34.837906,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057317,2.412263e+09,2015-04-07 03:29:09.000,138.644531,-34.837643,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057318,2.412263e+09,2015-04-07 03:38:05.000,138.644089,-34.837967,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057319,2.412263e+09,2015-04-07 03:48:52.000,138.644073,-34.837761,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000

In [5]:
classes = df['Hunt']
classes

0          Yes
1          Yes
2          Yes
3          Yes
4          Yes
          ...
1057315    Yes
1057316    Yes
1057317    Yes
1057318    Yes
1057319    Yes
Name: Hunt, Length: 1057320, dtype: object

comme prévu, nous avons 2 tableaux : 

* classes : soit les classes à prédire (`Hunt`)
* variables : soit les variables du tableau

## Création du modèle qualitatif

In [6]:
cls = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=60, 
    per_run_time_limit=120, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

*les param minimum pour la tâche* : 

- time_left_for_this_task= 2000 s
- per_run_time_limit=30 cycles
- n_jobs = 16 coeur
- memory_limit = 24 Go

### Génération des jeux de test, validation

pour notre entrainement, nous prenons des proportions de 67% de test et 33% de test

Les méthodes testées sont : 

* Forêt aléatoire
* Latent Dirichlet Allocation
* Multilayered Perceptron
* Baisien naif
* k plus proches voisins

### Dans un premier temps, nous allons utiliser seulement les données Quantitatives

#### gestion de la suppression des colonnes quantitatives

In [7]:
dfQuali = variables.drop(["event.id","timestamp","location.long","location.lat",
                          "animal.id","StartDate","StartHours","EndDate","EndHours"],
                         axis = 1).astype('category')

Crée le jeu de test qualitatif

In [8]:
variables_trainQ, variables_testQ, classes_trainQ, classes_testQ = train_test_split(
        																dfQuali, classes, test_size = 0.5, random_state=0)

Transformation de classesQ en `category` à la place de `object`

In [9]:
classes_testQ = classes_testQ.astype("category")
classes_trainQ = classes_trainQ.astype("category")

application des paramêtre afin de crée le modèle

In [10]:
cls.fit(variables_trainQ, classes_trainQ)

/usr/local/lib/python3.8/dist-packages/autosklearn/data/target_validator.py:187: UserWarning: Fitting transformer with a pandas series which has the dtype category. Inverse transform may not be able preserve dtype when converting to np.ndarray
  warnings.warn(

[WARNING] [2025-04-27 06:51:58,010:Client-AutoML(1):1a89c39e-2334-11f0-a0fd-121c485a7426] Time limit for a single run is higher than total time limit. Capping the limit for a single run to the total time given to SMAC (59.371650)
[WARNING] [2025-04-27 06:51:58,010:Client-AutoML(1):1a89c39e-2334-11f0-a0fd-121c485a7426] Capping the per_run_time_limit to 29.0 to have time for a least 2 models in each process.

Process pynisher function call:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 132, in _unique_python
    uniques = sorted(uniques_set)
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pynisher/limit_function_call.py", line 133, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/smbo.py", line 160, in _calculate_metafeatures_encoded
    result = calculate_all_metafeatures_encoded_labels(
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1115, in calculate_all_metafeatures_encoded_labels
    return calculate_all_metafeatures(
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1194, in calculate_all_metafeatures
    X_transformed = DPP.fit_transform(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/pipeline/components/data_preprocessing/feature_type.py", line 216, in fit
    self.column_transformer.fit(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 470, in fit
    self.fit_transform(X, y=y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 507, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 434, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 378, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 303, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/usr/local/lib/python3.8/dist-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/pipeline/components/data_preprocessing/categorical_encoding/encoding.py", line 29, in fit
    self.preprocessor.fit(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py", line 779, in fit
    self._fit(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py", line 90, in _fit
    cats = _unique(Xi)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 31, in _unique
    return _unique_python(values, return_inverse=return_inverse)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 138, in _unique_python
    raise TypeError("Encoders require their input to be uniformly "
TypeError: Encoders require their input to be uniformly strings or numbers. Got ['int', 'str']

[WARNING] [2025-04-27 06:51:59,097:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 412 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 102 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 367 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 262 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 37 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 605 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 88 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 426 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 524 not found
[WARNING] [2025-04-27 06:51:59,098:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 173 not found
[WARNING] [2025-04-27 06:51:59,099:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 206 not found
[WARNING] [2025-04-27 06:51:59,099:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 69 not found
[WARNING] [2025-04-27 06:51:59,099:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 668 not found
[WARNING] [2025-04-27 06:51:59,099:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 277 not found
[WARNING] [2025-04-27 06:51:59,099:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 657 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 694 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 518 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 414 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 232 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 386 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 378 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 14 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 238 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 108 not found
[WARNING] [2025-04-27 06:51:59,100:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 608 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 204 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 444 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 574 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 7 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 702 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 595 not found
[WARNING] [2025-04-27 06:51:59,101:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 631 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 492 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 563 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 506 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 288 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 467 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 430 not found
[WARNING] [2025-04-27 06:51:59,102:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 624 not found
[WARNING] [2025-04-27 06:51:59,103:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 628 not found
[WARNING] [2025-04-27 06:51:59,103:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 327 not found
[WARNING] [2025-04-27 06:51:59,103:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 579 not found
[WARNING] [2025-04-27 06:51:59,103:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 659 not found
[WARNING] [2025-04-27 06:51:59,103:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 302 not found
[WARNING] [2025-04-27 06:51:59,103:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 521 not found
[WARNING] [2025-04-27 06:51:59,104:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 40 not found
[WARNING] [2025-04-27 06:51:59,104:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 647 not found
[WARNING] [2025-04-27 06:51:59,104:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 690 not found
[WARNING] [2025-04-27 06:51:59,105:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 129 not found
[WARNING] [2025-04-27 06:51:59,105:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 347 not found
[WARNING] [2025-04-27 06:51:59,105:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 434 not found
[WARNING] [2025-04-27 06:51:59,105:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 264 not found
[WARNING] [2025-04-27 06:51:59,105:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 257 not found
[WARNING] [2025-04-27 06:51:59,106:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 532 not found
[WARNING] [2025-04-27 06:51:59,106:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 701 not found
[WARNING] [2025-04-27 06:51:59,106:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 329 not found
[WARNING] [2025-04-27 06:51:59,106:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 590 not found
[WARNING] [2025-04-27 06:51:59,106:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 150 not found
[WARNING] [2025-04-27 06:51:59,106:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 670 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 293 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 75 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 399 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 154 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 332 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 61 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 460 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 230 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 211 not found
[WARNING] [2025-04-27 06:51:59,107:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 358 not found
[WARNING] [2025-04-27 06:51:59,108:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 345 not found
[WARNING] [2025-04-27 06:51:59,108:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 17 not found
[WARNING] [2025-04-27 06:51:59,108:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 124 not found
[WARNING] [2025-04-27 06:51:59,108:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 298 not found
[WARNING] [2025-04-27 06:51:59,108:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 617 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 32 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 291 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 445 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 352 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 683 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 270 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 546 not found
[WARNING] [2025-04-27 06:51:59,109:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 571 not found
[WARNING] [2025-04-27 06:51:59,110:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 183 not found
[WARNING] [2025-04-27 06:51:59,110:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 112 not found
[WARNING] [2025-04-27 06:51:59,110:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 494 not found
[WARNING] [2025-04-27 06:51:59,110:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 375 not found
[WARNING] [2025-04-27 06:51:59,110:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 131 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 134 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 171 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 121 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 403 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 528 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 58 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 480 not found
[WARNING] [2025-04-27 06:51:59,111:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 243 not found
[WARNING] [2025-04-27 06:51:59,112:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 25 not found
[WARNING] [2025-04-27 06:51:59,113:Client-AutoMLSMBO(1)::1a89c39e-2334-11f0-a0fd-121c485a7426] Configuration 452 not found
[WARNING] [2025-04-27 06:52:01,145:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:01,336:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:01,434:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:01,524:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:04,030:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:04,106:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:05,919:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:07,866:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:07,733:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:09,442:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:11,532:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:13,493:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:16,344:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:16,425:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:16,474:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:18,329:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:20,419:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:22,262:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:24,154:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:25,971:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:27,769:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:29,799:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:31,584:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:33,467:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:35,264:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:35,365:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:36,791:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:38,593:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:40,274:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:42,327:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:44,268:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:46,409:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 06:52:46,459:Client-EnsembleBuilder] No runs were available to build an ensemble from

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=120,
                      time_left_for_this_task=60)

Ne fournis pas de résultats pertinant, potentielement par manque de temps de calcul (25 et 30min avait été testé)

In [11]:
cls.leaderboard()

          rank  ensemble_weight  type  cost duration
model_id
1            1              1.0  <NA>  <NA>     <NA>

Ici, nous voyons que le modèle n'est même pas arriver à faire une ligne (facteur séparateur)

In [12]:
predictions_Hunt = list(cls.predict(variables_testQ))

précision :

In [13]:
print("Accuracy score:", sklearn.metrics.accuracy_score(np.array(classes_testQ), predictions_Hunt))

Accuracy score: 0.14220292815798433

table des stats

In [14]:
print( sklearn.metrics.classification_report(classes_testQ, predictions_Hunt) )

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          NA       0.14      1.00      0.25     75177
          No       0.00      0.00      0.00     75219
         Yes       0.00      0.00      0.00    378264

    accuracy                           0.14    528660
   macro avg       0.05      0.33      0.08    528660
weighted avg       0.02      0.14      0.04    528660

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

décevant : on a un précision catastrophique.

Nous allons regarder la matrice de confusion pour potentiellement observer quel groupe est le mieu prédit

In [15]:
np.round( confusion_matrix(classes_testQ, predictions_Hunt), 3)

array([[ 75177,      0,      0],
       [ 75219,      0,      0],
       [378264,      0,      0]])

Le problème est clair : on prédit tout en une classe

## Tentative avec du quantitatif

### Ouverture du csv

In [4]:
dfQuanti = pd.read_csv('data/OutCatdataQuantiNormZ.csv', na_filter= False)
dfQuanti = dfQuanti.drop("Unnamed: 0", axis= 1)

/tmp/ipykernel_95801/2793842605.py:1: DtypeWarning: Columns (6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  dfQuanti = pd.read_csv('data/OutCatdataQuantiNormZ.csv', na_filter= False)

### Suppression des lignes ayant des Na

In [5]:
dfQuanti = dfQuanti[~np.any(dfQuanti == "NA",axis=1)]

### Création des sous jeux de données de test et d'entrainement

In [6]:
x = dfQuanti.drop('Hunt', axis=1).to_numpy().astype(np.float64)
y = dfQuanti.Hunt.astype(object)

y[y ==	-2.16472428387967] = "Na"
y[y == 	-0.78922734140023] = "No"
y[y ==   0.586269601079213]  = "Yes"

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size = 0.5, random_state=0)

### Établissement d'un modèle

In [19]:
cls_hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=900, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

Ajustment du modèle a notre jeu de données

In [20]:
cls_hunt.fit(x_train, y_train, dataset_name='Cat Data')

[WARNING] [2025-04-27 06:53:03,487:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 06:53:03,487:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 06:53:03,487:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 06:53:03,487:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 06:53:03,487:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 06:53:03,487:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 06:53:03,488:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 06:53:03,489:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 06:53:03,490:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 06:53:03,490:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 06:53:03,490:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 06:53:03,490:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 06:53:03,490:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 06:53:03,491:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 06:53:03,492:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 06:53:03,493:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 06:53:03,493:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 06:53:03,493:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 06:53:03,493:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 06:53:03,494:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 06:53:03,495:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 06:53:03,496:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 06:53:03,497:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 06:53:03,497:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 06:53:03,497:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 06:53:03,497:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 06:53:03,497:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 06:53:03,498:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 06:53:03,499:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 06:53:03,499:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 06:53:03,499:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 06:53:03,499:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 06:53:03,500:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 06:53:03,500:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 06:53:03,500:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 06:53:03,500:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 06:54:40,155:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:43,694:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:47,644:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:47,692:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:52,454:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:52,513:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:58,052:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:54:57,463:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:02,222:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:02,300:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:12,694:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:13,106:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:30,270:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:30,359:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:33,038:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:33,102:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:40,457:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:47,468:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:55:54,265:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:07,509:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:15,147:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:16,036:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:16,280:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:27,272:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:30,827:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:30,981:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:31,104:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:31,201:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:36,626:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:42,600:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:42,755:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:42,884:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:42,983:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:49,681:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:49,820:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:51,809:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:56:58,018:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:05,741:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:09,552:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:09,653:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:13,214:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:13,295:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:17,000:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:17,084:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:21,741:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:25,902:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:28,660:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:28,750:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:35,014:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:35,117:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:40,249:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:40,363:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:42,730:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:42,844:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:50,534:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:50,613:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:55,675:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:57:55,772:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:02,816:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:06,973:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:07,080:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:10,772:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:10,867:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:15,005:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 06:58:15,121:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=100,
                      time_left_for_this_task=900)

### Affichage des résultats

### Affichage des facteurs

In [21]:
cls_hunt.leaderboard()

          rank  ensemble_weight                 type      cost   duration
model_id
5            1             0.02  k_nearest_neighbors  0.000000  21.166709
56           4             0.02  k_nearest_neighbors  0.000000  43.436522
64           5             0.04  k_nearest_neighbors  0.000000  21.074136
68           7             0.02  k_nearest_neighbors  0.000000  36.099317
120         10             0.02  k_nearest_neighbors  0.000000  32.381468
129          9             0.04  k_nearest_neighbors  0.000000  41.220996
141          8             0.02  k_nearest_neighbors  0.000000  44.679728
144          6             0.02  k_nearest_neighbors  0.000000  17.541120
155          3             0.06  k_nearest_neighbors  0.000000  24.936812
165          2             0.04  k_nearest_neighbors  0.000000  18.845595
158         11             0.04  k_nearest_neighbors  0.000006  35.884436
156         12             0.02  k_nearest_neighbors  0.000017  43.381224
160         13             0.02  k_nearest_neighbors  0.000029  49.908920
67          14             0.08  k_nearest_neighbors  0.000069  23.171742
69          15             0.04  k_nearest_neighbors  0.000075  58.186825
16          16             0.02                  mlp  0.063939  51.764354
107         17             0.04                  lda  0.125319  11.663608
171         18             0.02                  lda  0.145634   7.184807
73          19             0.02                  lda  0.148442  12.687070
11          20             0.04                  lda  0.148828  16.390468
49          21             0.02          gaussian_nb  0.162779   9.254359
104         22             0.02                  lda  0.182103   9.437158
157         23             0.02          gaussian_nb  0.204137  39.063930
29          24             0.02                  lda  0.205809  79.649173
75          25             0.02                  lda  0.213926   4.096499
124         26             0.06          gaussian_nb  0.215442   6.029227
55          27             0.02                  lda  0.222452   5.659211
66          28             0.04                  lda  0.222815   6.994874
169         29             0.02                  lda  0.235256   5.464039
121         30             0.02          gaussian_nb  0.241546   5.364953
118         31             0.02          gaussian_nb  0.268681   8.109448
18          33             0.02                  mlp  0.279024  40.560583
134         32             0.06                  mlp  0.279024  66.702424

### Stockage des prédictions

In [22]:
predictions_Hunt = list(cls_hunt.predict(x_test))

### Affichage des stats

In [23]:
print( sklearn.metrics.classification_report(y_test, predictions_Hunt) )

              precision    recall  f1-score   support

          Na       1.00      1.00      1.00     72285
          No       1.00      1.00      1.00     75535
         Yes       1.00      1.00      1.00    377823

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

### Affichage de la matrice de confusion

In [24]:
np.round( confusion_matrix(y_test, predictions_Hunt), 3)

array([[ 72285,      0,      0],
       [     0,  75535,      0],
       [     0,      0, 377823]])

# Prédiction du nombre de proie par chats

## création des 2 matrices

In [7]:
x2 = dfQuanti.drop('N.pray', axis=1).to_numpy().astype(np.float64)
y2 = dfQuanti['N.pray'].astype(object)

### To-do ya des strings dans dfQuanti['N.pray'] 

on les supprimes en copiant dans une liste temp que les float

In [8]:
out = []
for i in y2 : 
    if type(i) == float:
        out.append(i)
    elif type(i) == str :
        out.append(float(i))

y2 = pd.Series(out).astype(object)

### transformer les nombre de poids normalisé en leur valeur d'origine

génération d'un dico de traduction

In [9]:
dictUnfoctor = {}

fooKeys = np.unique(y2)
fooVals = np.unique(df['N.pray'].astype(object))

In [10]:
for i in range(len(fooKeys)):
    dictUnfoctor[fooKeys[i]] = fooVals[i]

application du dico

In [11]:
for pos in range(len(y2)) : 
    y2[pos] = str(dictUnfoctor[y2[pos]])

## On a fini le formatage, c'est l'heure de faire le jeu de test et le jeu d'entrainement

In [12]:
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2,
                                                    test_size = 0.5, random_state=0)

## Configuration du modèle

In [31]:
cls_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=800, 
    per_run_time_limit=160, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

### Affinage du modèle

In [32]:
cls_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:10:29,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:10:29,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:10:29,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:10:29,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:10:29,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:10:29,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:10:29,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:10:29,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:10:29,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:10:29,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:10:29,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:10:29,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:10:29,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:10:29,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:10:29,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:10:29,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:10:29,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:10:29,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:10:29,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:10:29,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:10:29,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:10:29,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:10:29,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:10:29,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:10:29,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:10:29,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:10:29,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:10:29,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:10:29,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:10:29,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:10:29,174:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:10:29,174:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:10:29,175:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:10:33,407:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:13:00,455:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:05,496:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:09,782:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:14,469:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:14,566:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:19,945:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:23,162:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:23,215:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:23,338:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:23,445:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:23,487:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:26,237:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:26,355:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:32,890:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:32,948:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:39,046:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:13:39,090:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:01,079:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:10,239:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:17,727:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:17,850:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:24,469:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:24,573:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:34,520:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:14:34,628:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:03,417:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:11,258:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:18,564:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:19,174:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:37,015:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:42,024:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:46,365:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:50,875:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:55,073:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:15:57,288:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:03,268:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:08,634:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:13,187:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:13,259:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:13,368:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:18,476:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:18,570:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:19,946:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:20,033:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:24,587:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:24,688:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:27,590:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:27,681:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:36,085:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:40,674:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:40,915:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:40,993:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:49,619:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:49,789:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:50,000:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:16:56,957:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:17:02,655:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:17:26,146:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:17:26,376:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:17:37,618:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:17:49,777:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:17:55,448:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:18:02,369:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:18:07,274:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=160,
                      time_left_for_this_task=800)

## Affichage des résultats

### Affichage des facteurs

In [33]:
cls_Npray.leaderboard()

          rank  ensemble_weight                 type      cost    duration
model_id
6            1             0.08  k_nearest_neighbors  0.000000   19.668080
17          10             0.04  k_nearest_neighbors  0.000000   16.055765
50          11             0.04  k_nearest_neighbors  0.000000   30.312841
52           7             0.04  k_nearest_neighbors  0.000000   29.125421
66           8             0.02  k_nearest_neighbors  0.000000   23.377948
70           6             0.02  k_nearest_neighbors  0.000000   16.620502
82           5             0.02  k_nearest_neighbors  0.000000   18.944720
86           4             0.04  k_nearest_neighbors  0.000000   33.369854
88           3             0.04  k_nearest_neighbors  0.000000   24.788978
95           2             0.08  k_nearest_neighbors  0.000000   23.427880
99           9             0.04  k_nearest_neighbors  0.000000   12.195954
49          12             0.02  k_nearest_neighbors  0.000006   34.588246
79          14             0.04  k_nearest_neighbors  0.000017   20.456544
87          13             0.04  k_nearest_neighbors  0.000017   17.093452
97          15             0.02  k_nearest_neighbors  0.000029   33.303812
77          16             0.02  k_nearest_neighbors  0.000035   38.771355
31          17             0.02  k_nearest_neighbors  0.000110   57.720392
51          18             0.02  k_nearest_neighbors  0.000300   44.914465
61          19             0.06  k_nearest_neighbors  0.000357   56.899131
24          20             0.06  k_nearest_neighbors  0.001897   60.653155
35          21             0.02                  lda  0.013634   71.001002
94          22             0.02  k_nearest_neighbors  0.050253   10.994770
76          23             0.04  k_nearest_neighbors  0.155550  137.573277
54          24             0.02                  lda  0.553954    6.391445
92          25             0.04                  lda  0.575100   12.225056
30          26             0.08          gaussian_nb  0.645138    7.910928
57          27             0.02          gaussian_nb  0.645138    5.883587

On voit que la méthode avec les modeles les plus significatf sont : Ida et gaussian_nb

### Stockage des prédictions

In [34]:
predictions_Npray = list(cls_Npray.predict(x2_test))

### Affichage des stats

In [35]:
print( sklearn.metrics.classification_report(y2_test, predictions_Npray) )

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00    163262
           0       1.00      1.00      1.00    106831
           1       1.00      1.00      1.00     53779
          10       1.00      1.00      1.00     16599
          11       1.00      1.00      1.00      2699
          13       1.00      1.00      1.00      1214
          15       1.00      1.00      1.00      3493
          16       1.00      1.00      1.00       808
          17       1.00      1.00      1.00       561
          19       1.00      1.00      1.00      7307
           2       1.00      1.00      1.00     53685
           3       1.00      1.00      1.00     28708
           4       1.00      1.00      1.00     41843
           5       1.00      1.00      1.00     19360
           6       1.00      1.00      1.00     11099
           7       1.00      1.00      1.00      3248
           8       1.00      1.00      1.00      8978
           9       1.00      1.00      1.00      2169

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

1 de précision pour chaque classes

### Affichage de la matrice de confusion

In [36]:
np.round( confusion_matrix(y2_test, predictions_Npray), 3)

array([[163262,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0, 106831,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,  53779,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,  16599,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,   2699,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,   1214,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,   3493,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,    808,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
           561,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,   7307,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,  53685,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,  28708,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,  41843,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,  19360,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,  11099,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,   3248,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
          8978,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,   2169]])

problême trop fort : on a une matrice de test diagonalle : aucune mauvaise prédiction, 100% de vrai

donc possibilité de réduire le temps de calcul pour l'entrainement

# Dernière prédiction le temps passé à l'intérieur

## création des 2 matrices

In [13]:
x3 = dfQuanti.drop('Hrs.indors', axis=1).to_numpy().astype(np.float64)
y3 = dfQuanti['Hrs.indors'].astype(object)

on les supprimes en copiant dans une liste temp que les float

In [14]:
out = []
for i in y3 : 
    if type(i) == float:
        out.append((i))
    elif type(i) == str :
        out.append(float(i))

y3 = pd.Series(out).astype(object)

### transformer les nombre de poids normalisé en leur valeur d'origine

génération d'un dico de traduction

In [15]:
dictUnfoctor = {}

fooKeys = np.unique(y3)
fooVals = (df['Hrs.indors'].astype(object))

restriction des données sous forme de string

In [16]:
out = []
for i in fooVals : 
    if type(i) == float:
        out.append(str(i))
    elif type(i) != float :
        out.append((i))

fooVals = pd.unique(out).astype(object)

création dico de traduction

In [17]:
for i in range(len(fooKeys)):
    dictUnfoctor[fooKeys[i]] = fooVals[i]

application du dico

In [18]:
for pos in range(len(y3)) : 
    y3[pos] = str(dictUnfoctor[y3[pos]])

## On a fini le formatage, c'est l'heure de faire le jeu de test et le jeu d'entrainement

In [19]:
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3,
                                                    test_size = 0.5, random_state=0)

## Configuration du modèle

In [44]:
cls_HrsOut = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=600, 
    per_run_time_limit=160, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

### Affinage du modèle

In [45]:
cls_HrsOut.fit(x3_train, y3_train, dataset_name='Cat Data')

[WARNING] [2025-04-27 07:26:42,439:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:26:42,439:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:26:42,439:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:26:42,439:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:26:42,439:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:26:42,439:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:26:42,440:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:26:42,440:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:26:42,440:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:26:42,440:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:26:42,440:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:26:42,441:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:26:42,441:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:26:42,441:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:26:42,441:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:26:42,442:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:26:42,442:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:26:42,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:26:42,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:26:42,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:26:42,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:26:42,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:26:42,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:26:42,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:26:42,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:26:42,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:26:42,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:26:42,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:26:42,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:26:42,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:26:42,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:26:42,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:26:42,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:26:42,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:26:42,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:26:42,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:26:42,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:26:42,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:26:42,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:26:42,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:26:42,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:26:42,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:26:42,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:26:42,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:26:42,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:26:42,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:26:42,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:26:42,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:26:42,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:26:42,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:26:42,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:26:42,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:26:42,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:26:42,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:26:42,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:26:42,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:26:42,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:26:42,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:26:42,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:26:42,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:26:42,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:26:42,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:26:42,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:26:42,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:26:42,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:26:46,527:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:29:15,236:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:17,592:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:26,788:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:26,872:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:26,997:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:27,173:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:27,235:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:27,305:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:27,426:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:28,640:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:37,754:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:39,901:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:40,007:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:47,151:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:47,247:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:48,849:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:29:48,919:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:30:06,799:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:30:20,849:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:30:31,232:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:30:31,311:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:30:54,410:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:04,754:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:44,985:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:45,262:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:45,484:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:45,608:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:45,704:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:45,775:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:31:53,271:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:00,608:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:04,568:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:08,488:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:08,646:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:08,733:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:13,783:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:13,947:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:17,440:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:17,668:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:26,147:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:30,816:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:30,909:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:34,828:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:40,196:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:44,847:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:52,351:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:53,493:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:32:53,772:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:08,167:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:08,278:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:13,758:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:13,866:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:23,397:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:32,174:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:41,713:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:47,520:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:47,677:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:47,787:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:59,124:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:33:59,279:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:34:01,453:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:34:05,775:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:34:17,286:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:34:17,439:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=160,
                      time_left_for_this_task=600)

## Affichage des résultats

### Affichage des facteurs

In [46]:
cls_HrsOut.leaderboard()

          rank  ensemble_weight                 type      cost    duration
model_id
13           1             0.10  k_nearest_neighbors  0.000000   14.986565
68           2             0.02  k_nearest_neighbors  0.000000   12.584594
5            3             0.06  k_nearest_neighbors  0.000006   21.449710
55           8             0.04  k_nearest_neighbors  0.000012   22.666966
57           6             0.08  k_nearest_neighbors  0.000012   64.290606
58           4             0.02  k_nearest_neighbors  0.000012   23.218338
74           5             0.02  k_nearest_neighbors  0.000012   13.712613
77           7             0.04  k_nearest_neighbors  0.000012   18.076830
59           9             0.02  k_nearest_neighbors  0.000190   51.273522
25          10             0.08  k_nearest_neighbors  0.002081   70.824842
61          11             0.08  k_nearest_neighbors  0.007143   15.646194
34          12             0.02                  lda  0.135972   21.180671
45          13             0.04                  mlp  0.590700   87.306662
73          14             0.04          gaussian_nb  0.704783   43.879043
40          15             0.02                  lda  0.719812    7.015596
30          16             0.06                  lda  0.721507   12.830005
62          17             0.02                  lda  0.761279  109.949834
36          18             0.04                  lda  0.765603   20.166910
53          19             0.02          gaussian_nb  0.782431   11.973325
80          20             0.04          gaussian_nb  0.815539    7.393303
42          21             0.02                  lda  0.822365   57.280091
39          22             0.02                  lda  0.858563  137.025565
49          23             0.06                  mlp  0.874635  112.892838
65          24             0.04                  mlp  0.874635   84.593792

méthode donnant le plus de poids : k_nearest_neighbors

### Stockage des prédictions

In [47]:
predictions_HrsOut = list(cls_HrsOut.predict(x3_test))

plutot "long" car on test +500000 lignes

### Affichage des stats

In [48]:
print( sklearn.metrics.classification_report(y3_test, predictions_HrsOut) )

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6519
           1       1.00      1.00      1.00     65575
          10       1.00      1.00      1.00     41745
          12       1.00      1.00      1.00     43796
          14       1.00      1.00      1.00     13201
          15       1.00      1.00      1.00     36938
          16       1.00      1.00      1.00     16434
          18       1.00      1.00      1.00     53462
           2       1.00      1.00      1.00     52736
          20       1.00      1.00      1.00     12525
          23       1.00      1.00      1.00      7306
           3       1.00      1.00      1.00     20568
           4       1.00      1.00      1.00     10083
           5       1.00      1.00      1.00     23066
           6       1.00      1.00      1.00     13023
           7       1.00      1.00      1.00     11637
           8       1.00      1.00      1.00     29453
           9       1.00      1.00      1.00     64770
          NA       1.00      1.00      1.00      2806

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

### Affichage de la matrice de confusion

In [49]:
np.round( confusion_matrix(y3_test, predictions_HrsOut), 3)

array([[ 6519,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 65575,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0, 41745,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     2, 43794,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0, 13201,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0, 36938,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0, 16434,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0, 53462,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0, 52736,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
        12525,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,  7306,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0, 20568,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 10083,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0, 23066,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0, 13023,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0, 11637,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0, 29453,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0, 64770,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
         2806]])

# test optimisation, peut-on se contenter de forêt aléatoire pour le calcul (tentative réduction temps)

In [50]:
cls_fda_Hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=220, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest"]},
    memory_limit=24576)

cls_fda_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=220, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest"]},
    memory_limit=24576)

cls_fda_HrsOut = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=220, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest"]},
    memory_limit=24576)

## Affinage des modèles

### prédiction Chasse

In [51]:
cls_fda_Hunt.fit(x_train, y_train, dataset_name='Cat Data')

predictions_fda_Hunt = list(cls_fda_Hunt.predict(x_test))

cls_fda_Hunt.leaderboard()

[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:37:57,280:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 07:37:57,281:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 07:37:57,281:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 07:37:57,281:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 07:37:57,281:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:37:57,281:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:37:57,281:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 07:37:57,282:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:37:57,283:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:37:57,284:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:37:57,284:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:37:57,285:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:37:57,286:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 07:37:57,287:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 07:37:57,288:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 07:37:57,289:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:37:57,289:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 07:37:57,289:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:37:57,289:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 07:37:57,290:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:37:57,291:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 07:37:57,292:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:37:57,293:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:37:57,294:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:37:57,295:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:37:57,295:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:37:57,295:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:37:57,295:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:37:57,295:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 07:37:57,296:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:37:57,296:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:37:57,296:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 07:37:57,296:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:37:57,296:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:37:57,296:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 07:37:57,297:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 07:37:57,297:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:37:57,297:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 07:37:57,297:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 07:37:57,297:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:37:57,298:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:37:57,298:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 07:37:57,298:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:39:33,022:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:39:33,322:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:39:33,425:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:39:33,575:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:06,524:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:06,611:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:06,813:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:07,080:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:07,242:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:07,402:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:07,543:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:41:23,192:Client-EnsembleBuilder] No runs were available to build an ensemble from

          rank  ensemble_weight  type  cost duration
model_id
1            1              1.0  <NA>  <NA>     <NA>

résultats : peut pas faire d'arbre avec ces données

### prédiction N.pray

In [52]:
cls_fda_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

predictions_fda_Npray = list(cls_fda_Npray.predict(x2_test))

cls_fda_Npray.leaderboard()

[WARNING] [2025-04-27 07:41:34,039:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 07:41:34,039:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 07:41:34,039:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:41:34,039:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:41:34,039:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:41:34,040:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:41:34,041:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 07:41:34,042:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:41:34,043:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:41:34,044:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:41:34,045:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 07:41:34,046:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:41:34,047:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 07:41:34,048:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:41:34,049:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:41:34,050:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 07:41:34,051:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 07:41:34,052:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:41:34,053:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 07:41:34,054:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:41:34,054:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 07:41:34,054:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:41:34,054:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:41:34,054:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 07:41:34,054:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 07:41:34,055:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:41:34,055:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 07:41:34,055:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:41:34,055:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 07:41:34,055:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:41:34,055:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:41:34,056:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:41:34,056:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:41:34,056:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 07:41:34,056:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 07:41:34,057:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:43:09,699:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:43:10,025:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:43:10,132:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:44,956:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:45,065:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:45,304:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:45,556:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:45,737:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:45,921:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:57,306:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:57,419:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:57,589:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:57,825:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:58,087:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:44:58,306:Client-EnsembleBuilder] No runs were available to build an ensemble from

          rank  ensemble_weight  type  cost duration
model_id
1            1              1.0  <NA>  <NA>     <NA>

résultats : peut pas faire d'arbre avec ces données

### prédiction Hrs.indors

In [53]:
cls_fda_HrsOut.fit(x3_train, y3_train, dataset_name='Cat Data')

predictions_fda_HrsOut = list(cls_fda_HrsOut.predict(x3_test))

cls_fda_HrsOut.leaderboard()

[WARNING] [2025-04-27 07:45:10,213:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 07:45:10,213:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 07:45:10,213:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:45:10,213:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:45:10,213:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:45:10,214:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:45:10,215:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:45:10,216:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:45:10,216:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:45:10,216:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:45:10,216:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:45:10,216:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:45:10,216:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:45:10,217:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 07:45:10,217:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:45:10,217:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 07:45:10,217:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 07:45:10,218:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:45:10,219:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:45:10,219:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:45:10,219:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:45:10,219:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:45:10,219:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 07:45:10,220:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:45:10,221:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:45:10,222:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:45:10,223:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:45:10,224:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 07:45:10,224:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:45:10,224:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 07:45:10,224:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:45:10,224:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:45:10,224:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:45:10,225:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:45:10,226:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:45:10,227:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:45:10,228:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:45:10,229:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:45:10,230:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 07:45:10,230:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:45:10,230:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 07:45:10,230:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 07:45:10,231:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 07:45:10,231:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:45:10,231:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:45:10,232:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:45:10,232:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:45:10,233:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 07:45:10,233:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 07:45:10,233:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:46:43,709:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:46:43,968:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:46:44,092:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:46:44,239:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:18,937:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,039:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,166:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,278:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,499:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,633:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,763:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:19,879:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:35,168:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:35,307:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:35,439:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:35,562:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-27 07:48:36,066:Client-EnsembleBuilder] No runs were available to build an ensemble from

          rank  ensemble_weight  type  cost duration
model_id
1            1              1.0  <NA>  <NA>     <NA>

résultats : peut pas faire d'arbre avec ces données

## affichage des résultats

### Hunt

In [54]:
print( sklearn.metrics.classification_report(y_test, predictions_fda_Hunt) )

np.round( confusion_matrix(y_test, predictions_fda_HrsOut), 3)

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          Na       0.14      1.00      0.24     72285
          No       0.00      0.00      0.00     75535
         Yes       0.00      0.00      0.00    377823

    accuracy                           0.14    525643
   macro avg       0.05      0.33      0.08    525643
weighted avg       0.02      0.14      0.03    525643

array([[     0,      0,      0,      0],
       [ 72285,      0,      0,      0],
       [ 75535,      0,      0,      0],
       [377823,      0,      0,      0]])

### N.pray

In [55]:
print( sklearn.metrics.classification_report(y2_test, predictions_fda_Npray) )

np.round( confusion_matrix(y2_test, predictions_fda_Npray), 3)

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          -1       0.31      1.00      0.47    163262
           0       0.00      0.00      0.00    106831
           1       0.00      0.00      0.00     53779
          10       0.00      0.00      0.00     16599
          11       0.00      0.00      0.00      2699
          13       0.00      0.00      0.00      1214
          15       0.00      0.00      0.00      3493
          16       0.00      0.00      0.00       808
          17       0.00      0.00      0.00       561
          19       0.00      0.00      0.00      7307
           2       0.00      0.00      0.00     53685
           3       0.00      0.00      0.00     28708
           4       0.00      0.00      0.00     41843
           5       0.00      0.00      0.00     19360
           6       0.00      0.00      0.00     11099
           7       0.00      0.00      0.00      3248
           8       0.00      0.00      0.00      8978
           9       0.00      0.00      0.00      2169

    accuracy                           0.31    525643
   macro avg       0.02      0.06      0.03    525643
weighted avg       0.10      0.31      0.15    525643

array([[163262,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [106831,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 53779,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 16599,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  2699,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  1214,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  3493,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [   808,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [   561,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  7307,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 53685,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 28708,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 41843,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 19360,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [ 11099,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  3248,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  8978,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [  2169,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0]])

### Hrs.indors

In [56]:
print( sklearn.metrics.classification_report(y3_test, predictions_fda_HrsOut) )

np.round( confusion_matrix(y3_test, predictions_fda_HrsOut), 3)

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

           0       0.01      1.00      0.02      6519
           1       0.00      0.00      0.00     65575
          10       0.00      0.00      0.00     41745
          12       0.00      0.00      0.00     43796
          14       0.00      0.00      0.00     13201
          15       0.00      0.00      0.00     36938
          16       0.00      0.00      0.00     16434
          18       0.00      0.00      0.00     53462
           2       0.00      0.00      0.00     52736
          20       0.00      0.00      0.00     12525
          23       0.00      0.00      0.00      7306
           3       0.00      0.00      0.00     20568
           4       0.00      0.00      0.00     10083
           5       0.00      0.00      0.00     23066
           6       0.00      0.00      0.00     13023
           7       0.00      0.00      0.00     11637
           8       0.00      0.00      0.00     29453
           9       0.00      0.00      0.00     64770
          NA       0.00      0.00      0.00      2806

    accuracy                           0.01    525643
   macro avg       0.00      0.05      0.00    525643
weighted avg       0.00      0.01      0.00    525643

array([[ 6519,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [65575,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [41745,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [43796,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [13201,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [36938,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [16434,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [53462,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [52736,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [12525,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [ 7306,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [20568,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [10083,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [23066,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [13023,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [11637,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [29453,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [64770,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [ 2806,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0]])

## Conclu :

Impossibilité de faire un arbre pour prédire quelque soit la 3 prédiction

# test optimisation 2, peut-on se contenter de k plus proche voisins pour le calcul (tentative réduction temps)

In [32]:
cls_kN_Hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["k_nearest_neighbors"]},
    memory_limit=24576)

cls_kN_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["k_nearest_neighbors"]},
    memory_limit=24576)

cls_kN_HrsOut = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["k_nearest_neighbors"]},
    memory_limit=24576)

## Affinage des modèles

### prédiction Chasse

In [33]:
cls_kN_Hunt.fit(x_train, y_train, dataset_name='Cat Data')

predictions_kN_Hunt = list(cls_kN_Hunt.predict(x_test))

[WARNING] [2025-04-27 08:33:08,644:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:33:10,156:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:33:10,157:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:33:10,158:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:33:10,159:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:33:10,160:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:33:10,161:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:33:10,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:33:10,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:33:10,162:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:33:10,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:33:10,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 08:33:10,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:33:10,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 08:33:10,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 08:33:10,163:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:33:10,164:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:33:10,165:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:33:10,166:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:33:10,167:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:33:10,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:33:10,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:33:10,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:33:10,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:33:10,168:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:33:10,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:33:10,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 08:33:10,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:33:10,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:33:10,169:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:33:10,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:33:10,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:33:10,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:33:10,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:33:10,170:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:33:10,171:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:33:10,172:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:33:10,173:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:33:10,174:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:33:10,174:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:33:10,174:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:33:10,175:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:33:10,175:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 08:33:10,175:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:33:10,175:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 08:33:42,155:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:33:48,469:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:33:54,594:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:33:54,718:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:33:55,898:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:34:02,118:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:34:09,916:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 08:34:29,688:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

In [59]:
cls_kN_Hunt.leaderboard()

          rank  ensemble_weight                 type      cost   duration
model_id
3            1             0.16  k_nearest_neighbors  0.000000  34.553523
7            2             0.12  k_nearest_neighbors  0.000000  24.677164
9            3             0.18  k_nearest_neighbors  0.000000  30.720862
12           4             0.06  k_nearest_neighbors  0.000000  38.710556
25           5             0.06  k_nearest_neighbors  0.000000  70.377589
27           6             0.08  k_nearest_neighbors  0.000000  69.085729
31           7             0.06  k_nearest_neighbors  0.000000  31.255920
17           8             0.10  k_nearest_neighbors  0.000006  39.188300
29           9             0.06  k_nearest_neighbors  0.000144  42.360525
4           10             0.12  k_nearest_neighbors  0.000749  76.150861

### prédiction N.pray

In [60]:
cls_kN_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

predictions_kN_Npray = list(cls_kN_Npray.predict(x2_test))

[WARNING] [2025-04-27 07:53:58,970:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 07:54:00,442:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 07:54:00,442:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 07:54:00,442:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 07:54:00,443:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 07:54:00,444:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 07:54:00,445:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 07:54:00,446:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:54:00,447:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:54:00,448:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:54:00,449:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:54:00,450:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:54:00,451:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 07:54:00,452:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:54:00,453:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 07:54:00,454:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:54:00,455:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 07:54:00,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 07:54:00,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:54:00,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:54:00,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:54:00,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:54:00,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 07:54:20,693:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:29,452:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:34,798:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:34,895:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:34,972:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:45,091:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:45,277:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:54:52,752:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

In [61]:
cls_kN_Npray.leaderboard()

          rank  ensemble_weight                 type      cost   duration
model_id
3            1             0.16  k_nearest_neighbors  0.000000  29.903038
4            2             0.12  k_nearest_neighbors  0.000000  19.784661
10           3             0.18  k_nearest_neighbors  0.000000  33.792944
20           4             0.06  k_nearest_neighbors  0.000000  24.441357
27           5             0.06  k_nearest_neighbors  0.000000  13.280283
17           6             0.10  k_nearest_neighbors  0.000006  41.164173
22           7             0.08  k_nearest_neighbors  0.000006  38.883449
12           8             0.06  k_nearest_neighbors  0.000012  41.567254
23           9             0.06  k_nearest_neighbors  0.000023  10.584699
6           10             0.12  k_nearest_neighbors  0.001897  86.778798

### prédiction Hrs.indors

In [62]:
cls_kN_HrsOut.fit(x3_train, y3_train, dataset_name='Cat Data')

predictions_kN_HrsOut = list(cls_kN_HrsOut.predict(x3_test))

[WARNING] [2025-04-27 07:58:16,314:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 07:58:17,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 07:58:17,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 07:58:17,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 07:58:17,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 07:58:17,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 07:58:17,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 07:58:17,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 07:58:17,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 07:58:17,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 07:58:17,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 07:58:17,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 07:58:17,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 07:58:17,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 07:58:17,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 07:58:17,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 07:58:17,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 07:58:17,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 07:58:17,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 07:58:17,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 07:58:17,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 07:58:17,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 07:58:17,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 07:58:17,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 07:58:17,835:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 07:58:17,835:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 07:58:17,835:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 07:58:17,835:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 07:58:17,836:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 07:58:17,837:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 07:58:17,838:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 07:58:17,839:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 07:58:17,840:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 07:58:17,841:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 07:58:17,841:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 07:58:17,841:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 07:58:17,841:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 07:58:17,841:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 07:58:17,842:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 07:58:17,842:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 07:58:17,842:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 07:58:17,842:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 07:58:17,843:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 07:58:17,843:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 07:58:17,843:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 07:58:17,844:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 07:58:17,844:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 07:58:17,844:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 07:58:17,844:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 07:58:17,844:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 07:58:17,845:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 07:58:17,845:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 07:58:17,845:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 07:58:17,845:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 07:58:17,846:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 07:58:17,847:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 07:58:17,848:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 07:58:17,849:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 07:58:17,849:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 07:58:17,849:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 07:58:17,850:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 07:58:17,851:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 07:58:40,786:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:58:46,218:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:58:51,961:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:58:52,165:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:58:52,241:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:58:59,617:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:58:59,760:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-27 07:59:08,394:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

In [63]:
cls_kN_HrsOut.leaderboard()

          rank  ensemble_weight                 type      cost   duration
model_id
5            1             0.16  k_nearest_neighbors  0.000000  21.723667
20           2             0.06  k_nearest_neighbors  0.000000  30.577849
3            3             0.14  k_nearest_neighbors  0.000006  29.874283
10           4             0.16  k_nearest_neighbors  0.000006  29.773019
23           5             0.10  k_nearest_neighbors  0.000006  13.770110
30           6             0.06  k_nearest_neighbors  0.000006  29.848074
17           7             0.08  k_nearest_neighbors  0.000012  44.006118
25           8             0.06  k_nearest_neighbors  0.000017  17.193578
12           9             0.06  k_nearest_neighbors  0.000023  40.137983
6           10             0.12  k_nearest_neighbors  0.002081  81.565944

## affichage des résultats

### Hunt

In [34]:
print( sklearn.metrics.classification_report(y_test, predictions_kN_Hunt) )

np.round( confusion_matrix(y_test, predictions_kN_Hunt), 3)

              precision    recall  f1-score   support

          Na       1.00      1.00      1.00     72285
          No       1.00      1.00      1.00     75535
         Yes       1.00      1.00      1.00    377823

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

array([[ 72285,      0,      0],
       [     0,  75535,      0],
       [     0,      0, 377823]])

### N.pray

In [65]:
print( sklearn.metrics.classification_report(y2_test, predictions_kN_Npray) )

np.round( confusion_matrix(y2_test, predictions_kN_Npray), 3)

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00    163262
           0       1.00      1.00      1.00    106831
           1       1.00      1.00      1.00     53779
          10       1.00      1.00      1.00     16599
          11       1.00      1.00      1.00      2699
          13       1.00      1.00      1.00      1214
          15       1.00      1.00      1.00      3493
          16       1.00      1.00      1.00       808
          17       1.00      1.00      1.00       561
          19       1.00      1.00      1.00      7307
           2       1.00      1.00      1.00     53685
           3       1.00      1.00      1.00     28708
           4       1.00      1.00      1.00     41843
           5       1.00      1.00      1.00     19360
           6       1.00      1.00      1.00     11099
           7       1.00      1.00      1.00      3248
           8       1.00      1.00      1.00      8978
           9       1.00      1.00      1.00      2169

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

array([[163262,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0, 106831,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,  53779,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,  16599,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,   2699,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,   1214,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,   3493,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,    808,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
           561,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,   7307,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,  53685,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,  28708,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,  41843,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,  19360,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,  11099,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,   3248,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
          8978,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,   2169]])

### Hrs.indors

In [66]:
print( sklearn.metrics.classification_report(y3_test, predictions_kN_HrsOut) )

np.round( confusion_matrix(y3_test, predictions_kN_HrsOut), 3)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6519
           1       1.00      1.00      1.00     65575
          10       1.00      1.00      1.00     41745
          12       1.00      1.00      1.00     43796
          14       1.00      1.00      1.00     13201
          15       1.00      1.00      1.00     36938
          16       1.00      1.00      1.00     16434
          18       1.00      1.00      1.00     53462
           2       1.00      1.00      1.00     52736
          20       1.00      1.00      1.00     12525
          23       1.00      1.00      1.00      7306
           3       1.00      1.00      1.00     20568
           4       1.00      1.00      1.00     10083
           5       1.00      1.00      1.00     23066
           6       1.00      1.00      1.00     13023
           7       1.00      1.00      1.00     11637
           8       1.00      1.00      1.00     29453
           9       1.00      1.00      1.00     64770
          NA       1.00      1.00      1.00      2806

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

array([[ 6519,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 65575,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0, 41745,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     2, 43794,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0, 13201,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0, 36938,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0, 16434,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0, 53462,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0, 52736,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
        12525,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,  7306,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0, 20568,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 10083,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0, 23066,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0, 13023,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0, 11637,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0, 29453,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0, 64770,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
         2806]])

## Conclusion : 

Utiliser les k plus proches voisins donne des résultats bien plus rapidement tout aussi juste

	==> pas nécécaire de perdre de la puissance de calcul pour les autres méthodes

# test optimisation 3, peut-on se contenter du naïf Baésien pour le calcul (tentative réduction temps)

In [67]:
cls_nb_Hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["gaussian_nb"]},
    memory_limit=24576)

cls_nb_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["gaussian_nb"]},
    memory_limit=24576)

cls_nb_HrsOut = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["gaussian_nb"]},
    memory_limit=24576)

## Affinage des modèles

### prédiction Chasse

In [68]:
cls_nb_Hunt.fit(x_train, y_train, dataset_name='Cat Data')

predictions_nb_Hunt = list(cls_nb_Hunt.predict(x_test))

[WARNING] [2025-04-27 08:02:59,148:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:03:00,659:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:03:00,660:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:03:00,660:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:03:00,661:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 08:03:00,661:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:03:00,661:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:03:00,662:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:03:00,663:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:03:00,664:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:03:00,665:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:03:00,666:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:03:00,667:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:03:00,668:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:03:00,668:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 08:03:00,668:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:03:00,668:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:03:00,669:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:03:00,669:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:03:00,669:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:03:00,669:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:03:00,669:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:03:00,669:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:03:00,670:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:03:00,671:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:03:00,672:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:03:00,673:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:03:00,674:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:03:00,674:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:03:00,674:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:03:00,674:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:03:00,674:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:03:00,674:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:03:00,675:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:03:00,675:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:03:00,675:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:03:00,675:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:03:00,675:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 08:03:00,676:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:03:00,676:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:03:00,676:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:03:00,677:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:03:00,678:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:03:00,678:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:03:00,678:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:03:00,679:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:03:00,680:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:03:00,681:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:03:00,682:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:03:00,683:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:03:00,684:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found

In [69]:
cls_nb_Hunt.leaderboard()

          rank  ensemble_weight         type      cost   duration
model_id
42           1             0.04  gaussian_nb  0.141547  49.158720
27           2             0.12  gaussian_nb  0.147900   5.489612
11           3             0.02  gaussian_nb  0.149330   8.356408
23           4             0.02  gaussian_nb  0.149330   5.712638
66           5             0.10  gaussian_nb  0.149439   4.506705
39           6             0.02  gaussian_nb  0.156374  11.986636
5            7             0.04  gaussian_nb  0.156945  18.909016
2           11             0.04  gaussian_nb  0.162779   4.585874
4           13             0.02  gaussian_nb  0.162779   5.591912
6           12             0.04  gaussian_nb  0.162779   5.883921
20          14             0.04  gaussian_nb  0.162779   5.156622
33           9             0.06  gaussian_nb  0.162779   4.307868
46           8             0.02  gaussian_nb  0.162779   6.391376
57          10             0.02  gaussian_nb  0.162779   4.227877
34          15             0.02  gaussian_nb  0.175087  71.824510
8           16             0.04  gaussian_nb  0.175474   5.510164
17          17             0.04  gaussian_nb  0.179394  12.953782
7           18             0.04  gaussian_nb  0.181129   4.920801
25          19             0.02  gaussian_nb  0.188756  60.696428
18          20             0.02  gaussian_nb  0.210553   8.850076
41          21             0.02  gaussian_nb  0.216174   9.864580
48          22             0.08  gaussian_nb  0.216174  15.249730
50          23             0.06  gaussian_nb  0.216174   7.123651
44          24             0.02  gaussian_nb  0.220014  23.128404
15          25             0.02  gaussian_nb  0.221242   7.966347
52          26             0.02  gaussian_nb  0.232143   4.175762

### prédiction N.pray

In [70]:
cls_nb_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

predictions_nb_Npray = list(cls_nb_Npray.predict(x2_test))

[WARNING] [2025-04-27 08:06:34,336:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:06:35,998:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:06:35,998:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:06:35,998:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:06:35,999:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:06:36,000:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:06:36,001:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:06:36,002:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 08:06:36,003:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 08:06:36,004:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:06:36,005:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:06:36,005:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:06:36,005:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:06:36,005:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:06:36,005:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:06:36,005:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:06:36,006:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:06:36,006:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:06:36,006:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:06:36,006:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:06:36,007:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:06:36,008:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:06:36,009:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:06:36,010:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:06:36,011:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:06:36,012:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:06:36,012:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:06:36,012:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:06:36,012:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:06:36,012:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:06:36,013:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:06:36,013:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:06:36,013:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:06:36,013:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:06:36,014:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:06:36,014:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:06:36,014:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:06:36,014:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:06:36,015:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:06:36,015:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:06:36,015:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:06:36,015:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:06:36,015:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:06:36,015:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:06:36,016:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:06:36,016:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:06:36,016:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 08:06:36,016:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:06:36,017:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:06:36,017:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:06:36,018:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:06:36,018:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:06:36,018:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:06:36,018:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:06:36,018:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:06:36,019:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:06:36,019:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:06:36,019:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:06:36,019:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:06:36,019:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:06:36,019:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:06:36,020:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:06:36,021:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:06:36,022:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:06:36,023:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:06:36,024:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:06:36,024:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:06:36,024:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:06:36,024:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:06:36,025:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 08:06:36,025:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:06:36,025:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 08:06:36,025:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:06:36,025:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:06:36,025:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:06:36,026:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:06:36,026:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:06:36,026:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:06:36,026:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:06:36,026:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 08:06:42,192:Client-EnsembleBuilder] No models better than random - using Dummy losses!
	Models besides current dummy model: 0
	Dummy models: 1

In [71]:
cls_nb_Npray.leaderboard()

          rank  ensemble_weight         type      cost   duration
model_id
45           1             0.22  gaussian_nb  0.487392  26.777017
47           2             0.02  gaussian_nb  0.514043  23.356947
30           3             0.02  gaussian_nb  0.518033   5.238057
24           4             0.08  gaussian_nb  0.573970  32.354060
46           5             0.16  gaussian_nb  0.576288  30.306376
4            6             0.02  gaussian_nb  0.593571  37.151892
26           7             0.46  gaussian_nb  0.620389   3.282469
18           8             0.02  gaussian_nb  0.625001  12.675972

### prédiction Hrs.indors

In [72]:
cls_nb_HrsOut.fit(x3_train, y3_train, dataset_name='Cat Data')

predictions_nb_HrsOut = list(cls_nb_HrsOut.predict(x3_test))

[WARNING] [2025-04-27 08:09:59,685:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:10:01,299:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:10:01,299:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:10:01,300:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 08:10:01,300:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:10:01,300:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:10:01,300:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:10:01,301:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:10:01,301:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:10:01,301:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:10:01,301:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 615 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 707 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:10:01,302:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:10:01,303:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:10:01,304:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 08:10:01,305:Client-AutoMLSMBO(1)::Cat Data] Configuration 653 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 680 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:10:01,306:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:10:01,307:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:10:01,308:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:10:01,309:Client-AutoMLSMBO(1)::Cat Data] Configuration 138 not found
[WARNING] [2025-04-27 08:10:01,309:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:10:01,309:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:10:01,309:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:10:01,310:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:10:01,310:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:10:01,310:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:10:01,310:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:10:01,310:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:10:01,311:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:10:01,311:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:10:01,311:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:10:01,311:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:10:01,312:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:10:01,313:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:10:01,314:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:10:01,315:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:10:01,316:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:10:01,317:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:10:01,318:Client-AutoMLSMBO(1)::Cat Data] Configuration 254 not found
[WARNING] [2025-04-27 08:10:01,318:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:10:01,318:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:10:01,318:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:10:01,318:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 640 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:10:01,319:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:10:01,320:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:10:01,320:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:10:01,320:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:10:01,320:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:10:01,320:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 120 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 214 not found
[WARNING] [2025-04-27 08:10:01,321:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:10:01,322:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:10:01,322:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 08:10:01,322:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:10:01,322:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:10:01,322:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:10:01,322:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:10:01,323:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:10:01,323:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:10:01,323:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:10:01,323:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 08:10:01,323:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:10:01,323:Client-AutoMLSMBO(1)::Cat Data] Configuration 363 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:10:01,324:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found

In [73]:
cls_nb_HrsOut.leaderboard()

          rank  ensemble_weight         type      cost   duration
model_id
20           1             0.32  gaussian_nb  0.664532  13.342049
18           2             0.08  gaussian_nb  0.758304  10.848340
15           3             0.24  gaussian_nb  0.765049   9.024784
7            4             0.08  gaussian_nb  0.803744   6.021194
8            5             0.22  gaussian_nb  0.814616   6.521437
9            6             0.06  gaussian_nb  0.864501  16.356224

## affichage des résultats

### Hunt

In [74]:
print( sklearn.metrics.classification_report(y_test, predictions_nb_Hunt) )

np.round( confusion_matrix(y_test, predictions_nb_Hunt), 3)

              precision    recall  f1-score   support

          Na       0.71      0.66      0.68     72285
          No       0.73      0.72      0.72     75535
         Yes       0.93      0.95      0.94    377823

    accuracy                           0.88    525643
   macro avg       0.79      0.78      0.78    525643
weighted avg       0.87      0.88      0.88    525643

array([[ 47515,  10437,  14333],
       [ 10456,  54240,  10839],
       [  9243,   9515, 359065]])

### N.pray

In [75]:
print( sklearn.metrics.classification_report(y2_test, predictions_nb_Npray) )

np.round( confusion_matrix(y2_test, predictions_nb_Npray), 3)

              precision    recall  f1-score   support

          -1       0.88      0.81      0.85    163262
           0       0.43      0.61      0.51    106831
           1       0.53      0.23      0.33     53779
          10       0.45      0.53      0.49     16599
          11       0.20      0.61      0.30      2699
          13       1.00      1.00      1.00      1214
          15       1.00      0.83      0.91      3493
          16       1.00      0.99      0.99       808
          17       1.00      1.00      1.00       561
          19       0.79      0.55      0.65      7307
           2       0.43      0.49      0.45     53685
           3       0.44      0.17      0.24     28708
           4       0.47      0.44      0.45     41843
           5       0.32      0.35      0.34     19360
           6       0.42      0.35      0.38     11099
           7       0.22      0.76      0.34      3248
           8       0.68      0.61      0.64      8978
           9       1.00      1.00      1.00      2169

    accuracy                           0.57    525643
   macro avg       0.63      0.63      0.60    525643
weighted avg       0.60      0.57      0.57    525643

array([[132400,  14837,      0,    672,      0,      0,      0,      0,
             0,      0,   6870,   1308,   6018,    505,      0,      0,
           652,      0],
       [ 14415,  65108,   2335,   3887,   2262,      0,      0,      0,
             0,    462,   7158,      0,   3170,   6895,      0,   1139,
             0,      0],
       [  2670,  18905,  12602,   2813,   1281,      0,      0,      0,
             0,      0,   5263,   1018,   2926,   1831,      0,   3273,
          1197,      0],
       [     0,   3222,      1,   8855,      0,      0,      0,      0,
             0,      0,   3648,    139,      0,      3,      0,      0,
           731,      0],
       [     0,   1065,      0,      0,   1634,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      2,      0,      0,   1212,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,    601,      0,      0,      0,      0,   2892,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      9,      0,      0,      0,      0,      0,    799,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      2,      0,      0,      0,      0,      0,      0,
           559,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,   1458,      0,      0,      0,      0,      0,      0,
             0,   4035,   1814,      0,      0,      0,      0,      0,
             0,      0],
       [     0,  16812,   2648,    767,   1441,      0,      0,      0,
             0,      0,  26234,   2402,      8,    672,   2114,    587,
             0,      0],
       [   498,  10221,   3627,    512,      0,      0,      0,      0,
             0,      0,   3995,   4820,   3469,   1566,      0,      0,
             0,      0],
       [     0,   6800,   1809,   2127,      0,      0,      0,      0,
             0,    606,   5364,      0,  18303,   1398,   1655,   3780,
             1,      0],
       [     0,   6784,      0,      0,   1441,      0,      0,      0,
             0,      0,   1335,      0,   1421,   6843,   1536,      0,
             0,      0],
       [     0,   3527,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,   2598,   1099,   3853,      0,
            22,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,     18,      0,    770,      0,      0,   2460,
             0,      0],
       [     0,   1117,    721,      0,      0,      0,      0,      0,
             0,      0,      0,   1191,      0,    465,      0,      0,
          5484,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,   2169]])

### Hrs.indors

In [76]:
print( sklearn.metrics.classification_report(y3_test, predictions_nb_HrsOut) )

np.round( confusion_matrix(y3_test, predictions_nb_HrsOut), 3)

              precision    recall  f1-score   support

           0       0.57      0.67      0.62      6519
           1       0.53      0.34      0.41     65575
          10       0.19      0.20      0.19     41745
          12       0.60      0.32      0.42     43796
          14       0.22      0.40      0.28     13201
          15       0.22      0.67      0.33     36938
          16       0.44      0.25      0.32     16434
          18       0.35      0.07      0.11     53462
           2       0.57      0.35      0.43     52736
          20       0.20      0.87      0.33     12525
          23       0.22      0.91      0.36      7306
           3       0.29      0.24      0.27     20568
           4       0.20      0.72      0.31     10083
           5       0.62      0.21      0.31     23066
           6       0.31      0.49      0.38     13023
           7       0.36      0.67      0.47     11637
           8       0.82      0.68      0.75     29453
           9       0.20      0.01      0.02     64770
          NA       0.83      1.00      0.91      2806

    accuracy                           0.34    525643
   macro avg       0.41      0.48      0.38    525643
weighted avg       0.41      0.34      0.32    525643

array([[ 4385,   860,     0,     0,     0,     0,     0,     0,     0,
            0,   498,   636,     0,     0,     0,   140,     0,     0,
            0],
       [    0, 22096,  3121,  3709,  2614, 15522,  1711,     0,  2609,
         8958,     0,  2053,  1644,     0,  1010,   528,     0,     0,
            0],
       [    0,  1958,  8160,     0,  1267, 10107,     0,     0,   831,
         4191,  4007,  3349,  2763,     0,  1093,  2019,     0,  2000,
            0],
       [    0,   148,  1424, 14140,  3003,  7768,  1517,  1437,   801,
         3840,  2163,   418,  2651,     0,   619,  2208,     0,  1103,
          556],
       [    0,   672,     0,     0,  5243,  2854,     0,  1552,     0,
            0,  2880,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,  1003,   672,  1553,  1092, 24895,   607,     0,     0,
         3567,     0,  1468,  1669,     1,     1,   410,     0,     0,
            0],
       [  824,   397,   744,   633,     0,  4863,  4066,     0,   373,
         1374,  1580,   888,     0,     0,     0,   692,     0,     0,
            0],
       [  740,   548, 10069,     1,  2130, 13844,     0,  3636,  2279,
         5338,   855,  2384,  5068,  1587,  2374,  1510,  1099,     0,
            0],
       [    0,  4830,  7653,   465,  3756,  8699,     0,     0, 18288,
         3996,  2598,     0,  1349,     0,     0,  1102,     0,     0,
            0],
       [    0,     1,     0,     0,     0,     1,     0,     0,     0,
        10866,     0,     0,     0,     0,   932,   725,     0,     0,
            0],
       [    0,   226,     0,     0,     0,     0,     0,     0,     0,
            0,  6640,     0,   328,     0,     0,   112,     0,     0,
            0],
       [    0,     0,   752,     0,  2515,  7315,     0,     0,     0,
         1510,  1597,  4984,  1231,     0,   664,     0,     0,     0,
            0],
       [    0,  1476,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,  7233,  1374,     0,     0,     0,     0,
            0],
       [    0,  1172,  4018,     0,     0,  2435,     0,     0,     1,
            0,  3187,     0,   743,  4745,  2954,  2294,  1517,     0,
            0],
       [    0,     0,  1672,    18,  1718,  1187,     0,     0,   770,
            0,     0,     0,  1271,     0,  6387,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,  1374,   637,     0,
          502,     0,     0,   831,     0,   462,  7831,     0,     0,
            0],
       [  646,     0,  2445,   208,     0,  1621,     0,   587,     0,
         3085,     0,   731,     0,     0,     0,     0, 20130,     0,
            0],
       [ 1126,  6391,  3110,  2881,   606, 13069,     0,  2415,  6296,
         6440,  4074,     0,  9544,     1,  4025,  2283,  1757,   752,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
         2806]])

## Conclusion : 

Utiliser le naif bayésien donne des résultats bien plus rapidement mais bien plux faux

	==> pas nécécaire de perdre de la puissance de calcul pour les autres méthodes

# test optimisation 4, peut-on se contenter du lda (linear discrinant analysis) pour le calcul (tentative réduction temps)

In [20]:
cls_lda_Hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["lda"]},
    memory_limit=24576)

cls_lda_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["lda"]},
    memory_limit=24576)

cls_lda_HrsOut = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=200, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["lda"]},
    memory_limit=24576)

## Affinage des modèles

### prédiction Chasse

In [21]:
cls_lda_Hunt.fit(x_train, y_train, dataset_name='Cat Data')

predictions_lda_Hunt = list(cls_lda_Hunt.predict(x_test))

[WARNING] [2025-04-27 08:19:15,389:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:19:16,823:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:19:16,824:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:19:16,825:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:19:16,826:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:19:16,827:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:19:16,828:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:19:16,829:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:19:16,830:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:19:16,831:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:19:16,832:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:19:16,833:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 08:19:16,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:19:16,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:19:16,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:19:16,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:19:16,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:19:16,834:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 08:19:19,212:Client-EnsembleBuilder] No runs were available to build an ensemble from

In [22]:
cls_lda_Hunt.leaderboard()

          rank  ensemble_weight type      cost   duration
model_id
14           1             0.64  lda  0.065155  30.068367
9            2             0.02  lda  0.141420  14.633729
6            3             0.12  lda  0.155677   9.350123
11           4             0.02  lda  0.213926   9.104187
19           5             0.02  lda  0.213926   7.669858
23           6             0.02  lda  0.213926   4.523256
12           7             0.02  lda  0.220671   2.435512
18           8             0.04  lda  0.222452   4.279077
20           9             0.02  lda  0.222452   4.557085
13          10             0.08  lda  0.279024   9.142236

### prédiction N.pray

In [23]:
cls_lda_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

predictions_lda_Npray = list(cls_lda_Npray.predict(x2_test))

[WARNING] [2025-04-27 08:22:51,728:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:22:53,456:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:22:53,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:22:53,457:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:22:53,458:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:22:53,459:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:22:53,460:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:22:53,461:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 08:22:53,462:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:22:53,463:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:22:53,464:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:22:53,465:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 08:22:53,466:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:22:53,467:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:22:53,468:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:22:53,469:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:22:53,469:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:22:53,469:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:22:53,469:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:22:53,469:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:22:53,470:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 08:22:57,902:Client-EnsembleBuilder] No runs were available to build an ensemble from

In [24]:
cls_lda_Npray.leaderboard()

          rank  ensemble_weight type      cost   duration
model_id
14           1             0.24  lda  0.262052  46.252483
31           2             0.22  lda  0.321194  20.014729
21           3             0.16  lda  0.516741  15.853187
20           4             0.02  lda  0.553925  27.678117
27           5             0.30  lda  0.577320   9.872222
12           6             0.06  lda  0.585298   7.051345

### prédiction Hrs.indors

In [25]:
cls_lda_HrsOut.fit(x3_train, y3_train, dataset_name='Cat Data')

predictions_lda_HrsOut = list(cls_lda_HrsOut.predict(x3_test))

[WARNING] [2025-04-27 08:26:22,432:Client-AutoML(1):Cat Data] Capping the per_run_time_limit to 99.0 to have time for a least 2 models in each process.
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 509 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 322 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 543 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 19 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 553 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 448 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 99 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 470 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 56 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 193 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 83 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-27 08:26:23,950:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 197 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 97 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 160 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 48 not found
[WARNING] [2025-04-27 08:26:23,951:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 485 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 555 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 237 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 310 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 437 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 587 not found
[WARNING] [2025-04-27 08:26:23,952:Client-AutoMLSMBO(1)::Cat Data] Configuration 142 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 338 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 43 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 282 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 315 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 340 not found
[WARNING] [2025-04-27 08:26:23,953:Client-AutoMLSMBO(1)::Cat Data] Configuration 191 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 247 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 227 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 283 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 576 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 613 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 622 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 1 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 454 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 67 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-27 08:26:23,954:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-27 08:26:23,955:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-27 08:26:23,955:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-27 08:26:23,955:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-27 08:26:23,955:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-27 08:26:23,955:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-27 08:26:23,956:Client-AutoMLSMBO(1)::Cat Data] Configuration 515 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 188 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 71 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 266 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 222 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-27 08:26:23,957:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 22 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 369 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 422 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 184 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 663 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 162 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 486 not found
[WARNING] [2025-04-27 08:26:23,958:Client-AutoMLSMBO(1)::Cat Data] Configuration 560 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 566 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 149 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 585 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 473 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 91 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 512 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 674 not found
[WARNING] [2025-04-27 08:26:23,959:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 440 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 176 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 676 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 81 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 601 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 407 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 476 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 9 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 648 not found
[WARNING] [2025-04-27 08:26:23,960:Client-AutoMLSMBO(1)::Cat Data] Configuration 28 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 220 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 114 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 419 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 147 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 393 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 357 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 145 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 53 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 635 not found
[WARNING] [2025-04-27 08:26:23,961:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 313 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 172 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 251 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 536 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 382 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 538 not found
[WARNING] [2025-04-27 08:26:23,962:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 687 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 388 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 395 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 165 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 86 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 461 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 643 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 499 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 199 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 548 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 596 not found
[WARNING] [2025-04-27 08:26:23,963:Client-AutoMLSMBO(1)::Cat Data] Configuration 317 not found
[WARNING] [2025-04-27 08:26:23,964:Client-AutoMLSMBO(1)::Cat Data] Configuration 304 not found
[WARNING] [2025-04-27 08:26:23,964:Client-AutoMLSMBO(1)::Cat Data] Configuration 503 not found
[WARNING] [2025-04-27 08:26:23,964:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-27 08:26:23,964:Client-AutoMLSMBO(1)::Cat Data] Configuration 275 not found
[WARNING] [2025-04-27 08:26:27,847:Client-EnsembleBuilder] No runs were available to build an ensemble from

In [26]:
cls_lda_HrsOut.leaderboard()

          rank  ensemble_weight type      cost   duration
model_id
14           1             0.20  lda  0.337509  38.072702
24           2             0.14  lda  0.468402  10.479599
23           3             0.14  lda  0.600719  19.015767
20           4             0.02  lda  0.719812   8.733480
2            5             0.02  lda  0.721507   5.211615
19           6             0.02  lda  0.721507  19.498872
18           7             0.04  lda  0.732466   5.764215
30           8             0.12  lda  0.736628   5.778673
12           9             0.04  lda  0.763752   4.961150
22          10             0.18  lda  0.765724  16.880500
21          11             0.08  lda  0.767551  13.531749

## affichage des résultats

### Hunt

In [27]:
print( sklearn.metrics.classification_report(y_test, predictions_lda_Hunt) )

np.round( confusion_matrix(y_test, predictions_lda_Hunt), 3)

              precision    recall  f1-score   support

          Na       0.87      0.81      0.84     72285
          No       0.83      0.90      0.86     75535
         Yes       0.97      0.96      0.96    377823

    accuracy                           0.93    525643
   macro avg       0.89      0.89      0.89    525643
weighted avg       0.93      0.93      0.93    525643

array([[ 58856,   5646,   7783],
       [  3137,  68087,   4311],
       [  5923,   8558, 363342]])

### N.pray

In [28]:
print( sklearn.metrics.classification_report(y2_test, predictions_lda_Npray) )

np.round( confusion_matrix(y2_test, predictions_lda_Npray), 3)

              precision    recall  f1-score   support

          -1       0.91      0.89      0.90    163262
           0       0.67      0.70      0.68    106831
           1       0.72      0.66      0.69     53779
          10       0.71      0.83      0.76     16599
          11       0.51      0.61      0.56      2699
          13       0.24      1.00      0.39      1214
          15       0.55      1.00      0.71      3493
          16       0.47      1.00      0.64       808
          17       1.00      1.00      1.00       561
          19       0.82      0.68      0.74      7307
           2       0.60      0.74      0.66     53685
           3       0.80      0.50      0.62     28708
           4       0.78      0.79      0.78     41843
           5       0.67      0.56      0.61     19360
           6       1.00      0.59      0.74     11099
           7       0.87      0.76      0.81      3248
           8       0.69      0.74      0.72      8978
           9       1.00      0.58      0.74      2169

    accuracy                           0.75    525643
   macro avg       0.72      0.76      0.71    525643
weighted avg       0.77      0.75      0.76    525643

array([[144615,   6067,   1494,    672,      0,      0,   1204,      0,
             0,      0,   6154,      0,   1181,      0,      0,      0,
          1875,      0],
       [ 13064,  74969,   1026,   1331,   1544,    587,   1164,      0,
             0,    462,   7064,   1848,   1072,   1597,      0,      1,
          1102,      0],
       [  1153,   6498,  35661,    743,      0,   2508,      0,      0,
             0,      0,   4814,    450,   1593,      0,      0,    359,
             0,      0],
       [     0,   1828,      0,  13750,      0,      0,    472,      0,
             0,      0,    549,      0,      0,      0,      0,      0,
             0,      0],
       [     0,    340,      0,      0,   1634,      0,      0,      0,
             0,      0,    725,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,   1214,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,   3493,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,    808,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
           561,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [   230,    533,   1584,      0,      0,      0,      0,      0,
             0,   4960,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,   6751,   3785,    767,      0,      0,      0,      0,
             0,      0,  39648,      1,   1441,   1292,      0,      0,
             0,      0],
       [     0,  10532,    578,   1271,      0,      0,      0,      0,
             0,      0,   1766,  14413,      0,    148,      0,      0,
             0,      0],
       [     0,   2167,   2760,    831,      0,      0,      0,      1,
             0,    606,   1899,      0,  32868,    711,      0,      0,
             0,      0],
       [     0,   1754,      2,      0,      0,      0,      0,      0,
             0,      0,   2535,   1335,   2813,  10921,      0,      0,
             0,      0],
       [     0,      0,   2358,      0,      0,      0,      0,      0,
             0,      0,    884,      0,    241,   1099,   6517,      0,
             0,      0],
       [     0,      0,     18,      0,      0,      0,      0,      0,
             0,      0,      0,      0,    770,      0,      0,   2460,
             0,      0],
       [     0,   1117,      0,      0,      0,    721,      0,      0,
             0,      0,      0,      0,      0,    465,      0,      0,
          6675,      0],
       [     0,      0,      0,      0,      0,      0,      0,    904,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,   1265]])

### Hrs.indors

In [29]:
print( sklearn.metrics.classification_report(y3_test, predictions_lda_HrsOut) )

np.round( confusion_matrix(y3_test, predictions_lda_HrsOut), 3)

              precision    recall  f1-score   support

           0       0.86      0.77      0.81      6519
           1       0.50      0.78      0.61     65575
          10       0.68      0.52      0.59     41745
          12       0.71      0.68      0.69     43796
          14       0.86      0.83      0.84     13201
          15       0.58      0.75      0.66     36938
          16       0.72      0.53      0.61     16434
          18       0.74      0.70      0.72     53462
           2       0.70      0.60      0.65     52736
          20       0.76      0.61      0.68     12525
          23       0.41      0.70      0.51      7306
           3       0.91      0.76      0.83     20568
           4       0.62      0.92      0.74     10083
           5       0.96      0.63      0.76     23066
           6       0.99      0.73      0.84     13023
           7       0.82      0.72      0.76     11637
           8       1.00      0.81      0.90     29453
           9       0.63      0.57      0.60     64770
          NA       0.60      1.00      0.75      2806

    accuracy                           0.68    525643
   macro avg       0.74      0.72      0.71    525643
weighted avg       0.71      0.68      0.68    525643

array([[ 5021,   860,     0,     0,     0,     0,     0,     0,   140,
            0,   498,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 51065,  1182,  1403,     0,  4164,     0,  1744,   831,
            0,  1706,     0,     0,     1,     0,     0,     0,  3479,
            0],
       [    0,  6697, 21752,   951,  1086,  1963,     0,  3288,  2320,
            0,     0,     0,   181,     0,     0,   534,     0,  2763,
          210],
       [    0,  2001,   155, 29862,     0,  2004,  1976,     0,   603,
            1,   342,     0,   861,   418,     0,    32,     0,  5541,
            0],
       [    0,   672,     0,     0, 10964,    27,     0,  1538,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,  2030,   921,   734,     0, 27796,     0,     0,     0,
            0,   834,  1468,  1669,     0,     0,     0,     0,  1486,
            0],
       [  824,  3402,   177,     0,     0,     0,  8630,  2142,     0,
          492,     0,     0,     0,     0,     0,   692,     0,     0,
           75],
       [    0,  3002,  3918,  3646,     0,  2357,     0, 37235,   644,
            0,     0,     0,     0,     1,     0,     0,     0,  2659,
            0],
       [    0,  9012,  2752,   749,   768,  1602,     0,  1529, 31551,
            0,  2389,     0,  1349,     0,     0,     0,     0,  1035,
            0],
       [    0,  2496,     0,     0,     0,  1524,     0,     0,   855,
         7650,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,   329,     0,     0,     0,     0,     0,     0,  1662,
            0,  5090,     0,   225,     0,     0,     0,     0,     0,
            0],
       [    0,  3034,     0,   625,     0,     0,     0,     0,     0,
         1231,     0, 15550,     0,     0,   126,     0,     0,     2,
            0],
       [    0,   749,     0,     0,     0,     0,     0,     0,    38,
            0,     0,     0,  9296,     0,     0,     0,     0,     0,
            0],
       [    0,  1148,     0,     0,     0,  2381,     0,  1283,  2501,
            0,     0,     0,     0, 14418,     0,     0,     0,  1335,
            0],
       [    0,   788,     0,  1494,     0,     0,     0,     0,  1271,
            0,     0,     0,     0,     0,  9470,     0,     0,     0,
            0],
       [    0,     2,     0,   585,     0,     0,  1372,     0,     1,
            0,     0,     0,     0,     0,     0,  8344,     0,  1333,
            0],
       [    0,  1117,     0,     0,     0,  2176,     0,   587,     0,
            0,     0,     0,     0,     0,     0,     0, 23952,  1621,
            0],
       [    0, 12885,  1360,  2197,     0,  1817,     0,  1019,  2345,
          687,  1687,     0,  1407,   225,     0,   636,     0, 36936,
         1569],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
         2806]])

## Conclusion :