# Jupiter to automize clustering for Cats

In [8]:
import pandas as pd
import numpy as np
import sklearn.metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import autosklearn.classification

## I. Open the datasets

In [9]:
df = pd.read_csv('data/OutCatdata.csv', na_filter= False)
df = df.drop("Unnamed: 0", axis= 1)

/tmp/ipykernel_12/3855532020.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/OutCatdata.csv', na_filter= False)

/!\\ the NA values are dropped /!\\

## first look at the data

In [10]:
df

,event.id,timestamp,location.long,location.lat,animal.id,animal.life.stage,animal.reproductive.condition,animal.sex,Hunt,N.pray,Hrs.indors,N.neigbours,StartDate,StartHours,EndDate,EndHours
0,6.331585e+08,2015-04-19 01:02:59.000,138.649719,-34.953682,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
1,6.331585e+08,2015-04-19 01:06:59.000,138.649429,-34.953598,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
2,6.331585e+08,2015-04-19 01:09:53.000,138.649429,-34.954014,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
3,6.331585e+08,2015-04-19 01:12:45.000,138.649765,-34.954140,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
4,6.331585e+08,2015-04-19 01:15:37.000,138.649368,-34.954044,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057315,2.412263e+09,2015-04-07 03:08:57.000,138.644196,-34.837971,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057316,2.412263e+09,2015-04-07 03:19:06.000,138.644257,-34.837906,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057317,2.412263e+09,2015-04-07 03:29:09.000,138.644531,-34.837643,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057318,2.412263e+09,2015-04-07 03:38:05.000,138.644089,-34.837967,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057319,2.412263e+09,2015-04-07 03:48:52.000,138.644073,-34.837761,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000

### Split the datasets between classes to predict and data

In [11]:
variables = df.drop(['Hunt'], axis = 1)
variables

,event.id,timestamp,location.long,location.lat,animal.id,animal.life.stage,animal.reproductive.condition,animal.sex,N.pray,Hrs.indors,N.neigbours,StartDate,StartHours,EndDate,EndHours
0,6.331585e+08,2015-04-19 01:02:59.000,138.649719,-34.953682,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
1,6.331585e+08,2015-04-19 01:06:59.000,138.649429,-34.953598,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
2,6.331585e+08,2015-04-19 01:09:53.000,138.649429,-34.954014,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
3,6.331585e+08,2015-04-19 01:12:45.000,138.649765,-34.954140,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
4,6.331585e+08,2015-04-19 01:15:37.000,138.649368,-34.954044,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057315,2.412263e+09,2015-04-07 03:08:57.000,138.644196,-34.837971,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057316,2.412263e+09,2015-04-07 03:19:06.000,138.644257,-34.837906,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057317,2.412263e+09,2015-04-07 03:29:09.000,138.644531,-34.837643,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057318,2.412263e+09,2015-04-07 03:38:05.000,138.644089,-34.837967,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057319,2.412263e+09,2015-04-07 03:48:52.000,138.644073,-34.837761,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000

In [12]:
classes = df['Hunt']
classes

0          Yes
1          Yes
2          Yes
3          Yes
4          Yes
          ...
1057315    Yes
1057316    Yes
1057317    Yes
1057318    Yes
1057319    Yes
Name: Hunt, Length: 1057320, dtype: object

We have 2 resulting df : 

* classes consisting of the true Hunt status
* variables consisting of the factors

## Création du modèle qualitatif

In [13]:
cls = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=1000, 
    per_run_time_limit=120, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

*les param minimum pour la tâche* : 

- time_left_for_this_task= 2000 s
- per_run_time_limit=30 cycles
- n_jobs = 16 coeur
- memory_limit = 24 Go

### Génération des jeux de test, validation

pour notre entrainement, nous prenons des proportions de 67% de test et 33% de test

Les méthodes testées sont : 

* Forêt aléatoire
* Latent Dirichlet Allocation
* Multilayered Perceptron
* Baisien naif
* k plus proches voisins

### Dans un premier temps, nous allons utiliser seulement les données Quantitatives

#### gestion de la suppression des colonnes quantitatives

In [14]:
dfQuali = variables.drop(["event.id","timestamp","location.long","location.lat",
                          "animal.id","StartDate","StartHours","EndDate","EndHours"],
                         axis = 1).astype('category')

Crée le jeu de test qualitatif

In [15]:
variables_trainQ, variables_testQ, classes_trainQ, classes_testQ = train_test_split(
        																dfQuali, classes, test_size = 0.33, random_state=0)

Transformation de classesQ en `category` à la place de `object`

In [16]:
classes_testQ = classes_testQ.astype("category")
classes_trainQ = classes_trainQ.astype("category")

application des paramêtre afin de crée le modèle

In [17]:
cls.fit(variables_trainQ, classes_trainQ)

/usr/local/lib/python3.8/dist-packages/autosklearn/data/target_validator.py:187: UserWarning: Fitting transformer with a pandas series which has the dtype category. Inverse transform may not be able preserve dtype when converting to np.ndarray
  warnings.warn(
Process pynisher function call:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 132, in _unique_python
    uniques = sorted(uniques_set)
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pynisher/limit_function_call.py", line 133, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/smbo.py", line 160, in _calculate_metafeatures_encoded
    result = calculate_all_metafeatures_encoded_labels(
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1115, in calculate_all_metafeatures_encoded_labels
    return calculate_all_metafeatures(
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1194, in calculate_all_metafeatures
    X_transformed = DPP.fit_transform(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/pipeline/components/data_preprocessing/feature_type.py", line 216, in fit
    self.column_transformer.fit(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 470, in fit
    self.fit_transform(X, y=y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 507, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 434, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 378, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 303, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/usr/local/lib/python3.8/dist-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/pipeline/components/data_preprocessing/categorical_encoding/encoding.py", line 29, in fit
    self.preprocessor.fit(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py", line 779, in fit
    self._fit(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py", line 90, in _fit
    cats = _unique(Xi)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 31, in _unique
    return _unique_python(values, return_inverse=return_inverse)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 138, in _unique_python
    raise TypeError("Encoders require their input to be uniformly "
TypeError: Encoders require their input to be uniformly strings or numbers. Got ['int', 'str']

[WARNING] [2025-04-25 09:10:49,892:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 412 not found
[WARNING] [2025-04-25 09:10:49,892:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 102 not found
[WARNING] [2025-04-25 09:10:49,892:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 367 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 262 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 37 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 605 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 88 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 426 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 524 not found
[WARNING] [2025-04-25 09:10:49,893:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 173 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 206 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 69 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 668 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 277 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 657 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 694 not found
[WARNING] [2025-04-25 09:10:49,894:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 518 not found
[WARNING] [2025-04-25 09:10:49,895:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 414 not found
[WARNING] [2025-04-25 09:10:49,895:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 232 not found
[WARNING] [2025-04-25 09:10:49,895:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 386 not found
[WARNING] [2025-04-25 09:10:49,895:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 378 not found
[WARNING] [2025-04-25 09:10:49,895:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 14 not found
[WARNING] [2025-04-25 09:10:49,895:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 238 not found
[WARNING] [2025-04-25 09:10:49,896:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 108 not found
[WARNING] [2025-04-25 09:10:49,896:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 608 not found
[WARNING] [2025-04-25 09:10:49,897:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 204 not found
[WARNING] [2025-04-25 09:10:49,897:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 444 not found
[WARNING] [2025-04-25 09:10:49,897:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 574 not found
[WARNING] [2025-04-25 09:10:49,898:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 7 not found
[WARNING] [2025-04-25 09:10:49,898:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 702 not found
[WARNING] [2025-04-25 09:10:49,898:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 595 not found
[WARNING] [2025-04-25 09:10:49,898:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 631 not found
[WARNING] [2025-04-25 09:10:49,899:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 492 not found
[WARNING] [2025-04-25 09:10:49,899:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 563 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 506 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 467 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 288 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 430 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 624 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 628 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 327 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 579 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 659 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 302 not found
[WARNING] [2025-04-25 09:10:49,900:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 521 not found
[WARNING] [2025-04-25 09:10:49,901:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 40 not found
[WARNING] [2025-04-25 09:10:49,901:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 647 not found
[WARNING] [2025-04-25 09:10:49,901:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 690 not found
[WARNING] [2025-04-25 09:10:49,901:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 129 not found
[WARNING] [2025-04-25 09:10:49,901:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 347 not found
[WARNING] [2025-04-25 09:10:49,902:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 434 not found
[WARNING] [2025-04-25 09:10:49,902:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 264 not found
[WARNING] [2025-04-25 09:10:49,902:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 257 not found
[WARNING] [2025-04-25 09:10:49,904:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 532 not found
[WARNING] [2025-04-25 09:10:49,904:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 701 not found
[WARNING] [2025-04-25 09:10:49,905:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 329 not found
[WARNING] [2025-04-25 09:10:49,905:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 590 not found
[WARNING] [2025-04-25 09:10:49,905:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 150 not found
[WARNING] [2025-04-25 09:10:49,905:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 670 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 293 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 75 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 399 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 154 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 332 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 61 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 460 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 230 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 211 not found
[WARNING] [2025-04-25 09:10:49,906:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 358 not found
[WARNING] [2025-04-25 09:10:49,907:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 345 not found
[WARNING] [2025-04-25 09:10:49,907:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 17 not found
[WARNING] [2025-04-25 09:10:49,907:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 124 not found
[WARNING] [2025-04-25 09:10:49,907:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 298 not found
[WARNING] [2025-04-25 09:10:49,908:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 617 not found
[WARNING] [2025-04-25 09:10:49,908:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 32 not found
[WARNING] [2025-04-25 09:10:49,908:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 291 not found
[WARNING] [2025-04-25 09:10:49,908:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 445 not found
[WARNING] [2025-04-25 09:10:49,909:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 352 not found
[WARNING] [2025-04-25 09:10:49,909:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 683 not found
[WARNING] [2025-04-25 09:10:49,909:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 270 not found
[WARNING] [2025-04-25 09:10:49,909:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 546 not found
[WARNING] [2025-04-25 09:10:49,909:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 571 not found
[WARNING] [2025-04-25 09:10:49,910:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 183 not found
[WARNING] [2025-04-25 09:10:49,910:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 112 not found
[WARNING] [2025-04-25 09:10:49,910:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 494 not found
[WARNING] [2025-04-25 09:10:49,910:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 375 not found
[WARNING] [2025-04-25 09:10:49,910:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 131 not found
[WARNING] [2025-04-25 09:10:49,910:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 134 not found
[WARNING] [2025-04-25 09:10:49,911:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 171 not found
[WARNING] [2025-04-25 09:10:49,911:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 121 not found
[WARNING] [2025-04-25 09:10:49,911:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 403 not found
[WARNING] [2025-04-25 09:10:49,911:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 528 not found
[WARNING] [2025-04-25 09:10:49,912:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 58 not found
[WARNING] [2025-04-25 09:10:49,912:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 480 not found
[WARNING] [2025-04-25 09:10:49,912:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 243 not found
[WARNING] [2025-04-25 09:10:49,913:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 25 not found
[WARNING] [2025-04-25 09:10:49,914:Client-AutoMLSMBO(1)::278cb021-21b5-11f0-800c-d276ce1796e4] Configuration 452 not found
[WARNING] [2025-04-25 09:10:52,341:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:10:52,608:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:10:52,747:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:10:55,094:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:10:55,162:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:10:56,600:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:10:58,227:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:00,000:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:01,667:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:03,333:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:05,186:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:07,725:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:07,808:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:07,874:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:09,506:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:11,305:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:13,107:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:15,202:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:16,935:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:18,706:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:20,560:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:22,267:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:24,120:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:25,744:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:27,404:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:28,848:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:50,913:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:52,957:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:53,125:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:53,239:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:53,307:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:55,189:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:55,276:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:57,197:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:57,273:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:11:59,049:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:00,613:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:02,742:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:02,826:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:02,876:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:04,693:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:06,487:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:08,075:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:09,617:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:11,558:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:11,632:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:13,275:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:14,792:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:16,394:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:18,270:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:20,195:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:20,253:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:22,204:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:22,271:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:24,311:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:24,369:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:26,094:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:27,896:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:29,615:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:31,830:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:31,893:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:33,501:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:35,058:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:37,275:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:37,334:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:37,397:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:39,067:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:40,914:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:42,835:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:42,902:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:44,888:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:44,962:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:46,674:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:12:46,793:Client-EnsembleBuilder] No runs were available to build an ensemble from

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=120,
                      time_left_for_this_task=1000)

Ne fournis pas de résultats pertinant, potentielement par manqque de temps de calcul

In [18]:
cls.leaderboard()

          rank  ensemble_weight  type  cost duration
model_id
1            1              1.0  <NA>  <NA>     <NA>

Ici, nous voyons que le modèle n'est même pas arriver à faire une ligne

In [19]:
predictions_Hunt = list(cls.predict(variables_testQ))

précision :

In [20]:
print("Accuracy score:", sklearn.metrics.accuracy_score(np.array(classes_testQ), predictions_Hunt))

Accuracy score: 0.14220041499959876

table des stats

In [21]:
print( sklearn.metrics.classification_report(classes_testQ, predictions_Hunt) )

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          NA       0.14      1.00      0.25     49616
          No       0.00      0.00      0.00     49743
         Yes       0.00      0.00      0.00    249557

    accuracy                           0.14    348916
   macro avg       0.05      0.33      0.08    348916
weighted avg       0.02      0.14      0.04    348916

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

décevant : on a un précision catastrophique.

Nous allons regarder la matrice de confusion pour potentiellement observer quel groupe est le mieu prédit

In [22]:
np.round( confusion_matrix(classes_testQ, predictions_Hunt), 3)

array([[ 49616,      0,      0],
       [ 49743,      0,      0],
       [249557,      0,      0]])

Le problème est clair : on prédit tout en une classe

## Tentative avec du quantitatif

### Ouverture du csv

In [23]:
dfQuanti = pd.read_csv('data/OutCatdataQuantiNormZ.csv', na_filter= False)
dfQuanti = dfQuanti.drop("Unnamed: 0", axis= 1)

/tmp/ipykernel_12/2793842605.py:1: DtypeWarning: Columns (6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  dfQuanti = pd.read_csv('data/OutCatdataQuantiNormZ.csv', na_filter= False)

### Suppression des lignes ayant des Na

In [24]:
dfQuanti = dfQuanti[~np.any(dfQuanti == "NA",axis=1)]

### Création des sous jeux de données de test et d'entrainement

In [25]:
x = dfQuanti.drop('Hunt', axis=1).to_numpy().astype(np.float64)
y = dfQuanti.Hunt.astype(object)

y[y ==	-2.16472428387967] = "Na"
y[y == 	-0.78922734140023] = "No"
y[y ==   0.586269601079213]  = "Yes"

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size = 0.33, random_state=0)

### Établissement d'un modèle

In [26]:
cls_hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=900, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

Ajustment du modèle a notre jeu de données

In [27]:
cls_hunt.fit(x_train, y_train, dataset_name='Cat Data')

[WARNING] [2025-04-25 09:33:45,137:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-25 09:33:45,138:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-25 09:33:45,138:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-25 09:33:45,138:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-25 09:33:45,138:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-25 09:33:45,138:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-25 09:33:45,139:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-25 09:33:45,140:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-25 09:33:45,141:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-25 09:33:45,141:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-25 09:33:45,141:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-25 09:33:45,141:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-25 09:33:45,141:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-25 09:33:45,142:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-25 09:33:45,143:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-25 09:33:45,143:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-25 09:33:45,143:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-25 09:33:45,143:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-25 09:33:45,143:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-25 09:33:45,143:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-25 09:33:45,144:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-25 09:33:45,144:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-25 09:33:45,145:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-25 09:33:45,146:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-25 09:33:45,147:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-25 09:33:45,148:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-25 09:33:45,148:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-25 09:33:45,148:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-25 09:33:45,148:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-25 09:33:45,148:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-25 09:33:45,149:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-25 09:33:45,150:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-25 09:33:45,150:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-25 09:33:45,150:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-25 09:33:45,150:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-25 09:33:45,151:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-25 09:33:45,151:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-25 09:33:45,151:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-25 09:33:45,151:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-25 09:34:08,101:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 09:35:26,455:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:30,388:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:33,860:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:33,919:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:34,018:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:34,087:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:34,171:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:39,057:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:42,923:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:46,095:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:46,125:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:52,039:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:55,487:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:35:58,491:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:02,502:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:02,541:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:10,546:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:10,595:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:39,869:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:40,401:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:44,487:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:48,370:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:36:58,416:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:02,312:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:02,354:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:06,872:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:10,996:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:14,023:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:14,096:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:14,158:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:14,222:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:14,281:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:20,129:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:24,737:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:30,705:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:33,376:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:33,440:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:37,296:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:43,826:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:43,997:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:44,114:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:51,431:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:51,559:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:52,262:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:37:59,022:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:03,839:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:03,921:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:28,426:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:28,517:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:41,034:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:41,102:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:46,872:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:47,045:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:47,156:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:52,125:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:52,248:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:38:55,015:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:00,579:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:00,654:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:04,693:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:10,746:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:16,620:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:22,176:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 09:39:24,945:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=100,
                      time_left_for_this_task=900)

## Affichage des résultats

### Affichage des facteurs

In [28]:
cls_hunt.leaderboard()

          rank  ensemble_weight                 type      cost   duration
model_id
5            1             0.04  k_nearest_neighbors  0.000000  41.423518
85           4             0.02  k_nearest_neighbors  0.000000  97.328940
95           3             0.06  k_nearest_neighbors  0.000000  25.023483
97           2             0.02  k_nearest_neighbors  0.000000  85.988688
99           6             0.04  k_nearest_neighbors  0.000000  56.883847
100         11             0.02  k_nearest_neighbors  0.000000  96.171647
103          5             0.06  k_nearest_neighbors  0.000000  57.836018
110          8             0.06  k_nearest_neighbors  0.000000  32.980234
111          7             0.08  k_nearest_neighbors  0.000000  49.757138
121          9             0.02  k_nearest_neighbors  0.000000  32.745295
122         10             0.04  k_nearest_neighbors  0.000000  42.123322
112         13             0.02  k_nearest_neighbors  0.000004  46.456833
119         12             0.02  k_nearest_neighbors  0.000004  46.148650
16          14             0.06                  mlp  0.068577  72.788818
36          15             0.02                  lda  0.142601  44.983879
51          16             0.02                  lda  0.143453  20.591588
70          17             0.06                  lda  0.143453  25.965030
142         18             0.04                  lda  0.150818  12.180698
74          19             0.02                  mlp  0.170027  96.370939
143         20             0.02          gaussian_nb  0.170776   8.036712
31          22             0.02                  lda  0.214895   5.531387
55          21             0.02                  lda  0.214895   8.410710
84          23             0.04                  lda  0.214895   6.528015
87          24             0.04                  lda  0.214895   7.251528
66          25             0.04          gaussian_nb  0.216332  56.704742
52          26             0.02          gaussian_nb  0.243354   6.859191
18          28             0.02                  mlp  0.279626  69.510045
49          27             0.02                  lda  0.279626   7.545857
114         29             0.02                  lda  0.289190   6.774078
139         30             0.02          gaussian_nb  0.348048  36.846190

### Stockage des prédictions

In [29]:
predictions_Hunt = list(cls_hunt.predict(x_test))

### Affichage des stats

In [30]:
print( sklearn.metrics.classification_report(y_test, predictions_Hunt) )

              precision    recall  f1-score   support

          Na       1.00      1.00      1.00     47640
          No       1.00      1.00      1.00     49890
         Yes       1.00      1.00      1.00    249395

    accuracy                           1.00    346925
   macro avg       1.00      1.00      1.00    346925
weighted avg       1.00      1.00      1.00    346925

### Affichage de la matrice de confusion

In [31]:
np.round( confusion_matrix(y_test, predictions_Hunt), 3)

array([[ 47640,      0,      0],
       [     0,  49890,      0],
       [     0,      0, 249395]])

# Prédiction du nombre de proie par chats

## création des 2 matrices

In [101]:
x2 = dfQuanti.drop('N.pray', axis=1).to_numpy().astype(np.float64)
y2 = dfQuanti['N.pray'].astype(object)

### To-do ya des strings dans dfQuanti['N.pray'] 

on les supprimes en copiant dans une liste temp que les float

In [102]:
out = []
for i in y2 : 
    if type(i) == float:
        out.append(i)
    elif type(i) == str :
        out.append(float(i))

y2 = pd.array(out).astype(object)

## On a fini le formatage, c'est l'heure de faire le jeu de test et le jeu d'entrainement

In [103]:
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2,
                                                    test_size = 0.33, random_state=0)

## Configuration du modèle

In [104]:
cls_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=900, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

### Affinage du modèle

In [105]:
cls_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

ValueError: Classification with data of type unknown is not supported. Supported types are ['binary', 'multiclass', 'multilabel-indicator']. You can find more information about scikit-learn data types in: https://scikit-learn.org/stable/modules/multiclass.html

## Affichage des résultats

### Affichage des facteurs

In [ ]:
cls_Npray.leaderboard()

### Stockage des prédictions

In [ ]:
predictions_Npray = list(cls_Npray.predict(x2_test))

### Affichage des stats

In [ ]:
print( sklearn.metrics.classification_report(y2_test, predictions_Npray) )

### Affichage de la matrice de confusion

In [ ]:
np.round( confusion_matrix(y2_test, predictions_Npray), 3)