# Jupiter to automize clustering for Cats

In [2]:
import pandas as pd
import numpy as np
import sklearn.metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import autosklearn.classification

## Overture des données

In [ ]:
df = pd.read_csv('data/OutCatdata.csv', na_filter= False)
df = df.drop("Unnamed: 0", axis= 1)

/tmp/ipykernel_37744/3855532020.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/OutCatdata.csv', na_filter= False)

/!\\ the NA values are dropped /!\\

## observation des données

In [4]:
df

,event.id,timestamp,location.long,location.lat,animal.id,animal.life.stage,animal.reproductive.condition,animal.sex,Hunt,N.pray,Hrs.indors,N.neigbours,StartDate,StartHours,EndDate,EndHours
0,6.331585e+08,2015-04-19 01:02:59.000,138.649719,-34.953682,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
1,6.331585e+08,2015-04-19 01:06:59.000,138.649429,-34.953598,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
2,6.331585e+08,2015-04-19 01:09:53.000,138.649429,-34.954014,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
3,6.331585e+08,2015-04-19 01:12:45.000,138.649765,-34.954140,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
4,6.331585e+08,2015-04-19 01:15:37.000,138.649368,-34.954044,Princess,0 years,Sterilized,f,Yes,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057315,2.412263e+09,2015-04-07 03:08:57.000,138.644196,-34.837971,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057316,2.412263e+09,2015-04-07 03:19:06.000,138.644257,-34.837906,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057317,2.412263e+09,2015-04-07 03:29:09.000,138.644531,-34.837643,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057318,2.412263e+09,2015-04-07 03:38:05.000,138.644089,-34.837967,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057319,2.412263e+09,2015-04-07 03:48:52.000,138.644073,-34.837761,Tiger,5 years,Sterilized,m,Yes,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000

### Split the datasets between classes to predict and data

In [5]:
variables = df.drop(['Hunt'], axis = 1)
variables

,event.id,timestamp,location.long,location.lat,animal.id,animal.life.stage,animal.reproductive.condition,animal.sex,N.pray,Hrs.indors,N.neigbours,StartDate,StartHours,EndDate,EndHours
0,6.331585e+08,2015-04-19 01:02:59.000,138.649719,-34.953682,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
1,6.331585e+08,2015-04-19 01:06:59.000,138.649429,-34.953598,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
2,6.331585e+08,2015-04-19 01:09:53.000,138.649429,-34.954014,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
3,6.331585e+08,2015-04-19 01:12:45.000,138.649765,-34.954140,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
4,6.331585e+08,2015-04-19 01:15:37.000,138.649368,-34.954044,Princess,0 years,Sterilized,f,6,8,1,2015-04-18,16:02:59.000,2015-04-23,19:05:03.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057315,2.412263e+09,2015-04-07 03:08:57.000,138.644196,-34.837971,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057316,2.412263e+09,2015-04-07 03:19:06.000,138.644257,-34.837906,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057317,2.412263e+09,2015-04-07 03:29:09.000,138.644531,-34.837643,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057318,2.412263e+09,2015-04-07 03:38:05.000,138.644089,-34.837967,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000
1057319,2.412263e+09,2015-04-07 03:48:52.000,138.644073,-34.837761,Tiger,5 years,Sterilized,m,1,10,1,2015-04-01,01:32:24.000,2015-04-07,03:54:13.000

In [6]:
classes = df['Hunt']
classes

0          Yes
1          Yes
2          Yes
3          Yes
4          Yes
          ...
1057315    Yes
1057316    Yes
1057317    Yes
1057318    Yes
1057319    Yes
Name: Hunt, Length: 1057320, dtype: object

We have 2 resulting df : 

* classes consisting of the true Hunt status
* variables consisting of the factors

## Création du modèle qualitatif

In [7]:
cls = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=60, 
    per_run_time_limit=120, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

*les param minimum pour la tâche* : 

- time_left_for_this_task= 2000 s
- per_run_time_limit=30 cycles
- n_jobs = 16 coeur
- memory_limit = 24 Go

### Génération des jeux de test, validation

pour notre entrainement, nous prenons des proportions de 67% de test et 33% de test

Les méthodes testées sont : 

* Forêt aléatoire
* Latent Dirichlet Allocation
* Multilayered Perceptron
* Baisien naif
* k plus proches voisins

### Dans un premier temps, nous allons utiliser seulement les données Quantitatives

#### gestion de la suppression des colonnes quantitatives

In [8]:
dfQuali = variables.drop(["event.id","timestamp","location.long","location.lat",
                          "animal.id","StartDate","StartHours","EndDate","EndHours"],
                         axis = 1).astype('category')

Crée le jeu de test qualitatif

In [9]:
variables_trainQ, variables_testQ, classes_trainQ, classes_testQ = train_test_split(
        																dfQuali, classes, test_size = 0.5, random_state=0)

Transformation de classesQ en `category` à la place de `object`

In [10]:
classes_testQ = classes_testQ.astype("category")
classes_trainQ = classes_trainQ.astype("category")

application des paramêtre afin de crée le modèle

In [11]:
cls.fit(variables_trainQ, classes_trainQ)

/usr/local/lib/python3.8/dist-packages/autosklearn/data/target_validator.py:187: UserWarning: Fitting transformer with a pandas series which has the dtype category. Inverse transform may not be able preserve dtype when converting to np.ndarray
  warnings.warn(

[WARNING] [2025-04-25 16:32:04,497:Client-AutoML(1):cb431fdc-21f2-11f0-9370-423b658c063e] Time limit for a single run is higher than total time limit. Capping the limit for a single run to the total time given to SMAC (59.374212)
[WARNING] [2025-04-25 16:32:04,497:Client-AutoML(1):cb431fdc-21f2-11f0-9370-423b658c063e] Capping the per_run_time_limit to 29.0 to have time for a least 2 models in each process.

Process pynisher function call:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 132, in _unique_python
    uniques = sorted(uniques_set)
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pynisher/limit_function_call.py", line 133, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/smbo.py", line 160, in _calculate_metafeatures_encoded
    result = calculate_all_metafeatures_encoded_labels(
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1115, in calculate_all_metafeatures_encoded_labels
    return calculate_all_metafeatures(
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1194, in calculate_all_metafeatures
    X_transformed = DPP.fit_transform(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/pipeline/components/data_preprocessing/feature_type.py", line 216, in fit
    self.column_transformer.fit(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 470, in fit
    self.fit_transform(X, y=y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 507, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/compose/_column_transformer.py", line 434, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 378, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 303, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/usr/local/lib/python3.8/dist-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.8/dist-packages/autosklearn/pipeline/components/data_preprocessing/categorical_encoding/encoding.py", line 29, in fit
    self.preprocessor.fit(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py", line 779, in fit
    self._fit(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py", line 90, in _fit
    cats = _unique(Xi)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 31, in _unique
    return _unique_python(values, return_inverse=return_inverse)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_encode.py", line 138, in _unique_python
    raise TypeError("Encoders require their input to be uniformly "
TypeError: Encoders require their input to be uniformly strings or numbers. Got ['int', 'str']

[WARNING] [2025-04-25 16:32:05,525:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 412 not found
[WARNING] [2025-04-25 16:32:05,526:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 102 not found
[WARNING] [2025-04-25 16:32:05,526:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 367 not found
[WARNING] [2025-04-25 16:32:05,526:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 262 not found
[WARNING] [2025-04-25 16:32:05,526:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 37 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 605 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 88 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 426 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 524 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 173 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 206 not found
[WARNING] [2025-04-25 16:32:05,527:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 69 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 668 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 277 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 657 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 694 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 518 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 414 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 232 not found
[WARNING] [2025-04-25 16:32:05,528:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 386 not found
[WARNING] [2025-04-25 16:32:05,529:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 378 not found
[WARNING] [2025-04-25 16:32:05,529:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 14 not found
[WARNING] [2025-04-25 16:32:05,529:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 238 not found
[WARNING] [2025-04-25 16:32:05,529:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 108 not found
[WARNING] [2025-04-25 16:32:05,530:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 608 not found
[WARNING] [2025-04-25 16:32:05,530:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 204 not found
[WARNING] [2025-04-25 16:32:05,531:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 444 not found
[WARNING] [2025-04-25 16:32:05,531:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 574 not found
[WARNING] [2025-04-25 16:32:05,531:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 7 not found
[WARNING] [2025-04-25 16:32:05,531:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 702 not found
[WARNING] [2025-04-25 16:32:05,532:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 595 not found
[WARNING] [2025-04-25 16:32:05,532:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 631 not found
[WARNING] [2025-04-25 16:32:05,532:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 492 not found
[WARNING] [2025-04-25 16:32:05,532:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 563 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 506 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 288 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 467 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 430 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 624 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 628 not found
[WARNING] [2025-04-25 16:32:05,533:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 327 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 579 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 659 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 302 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 521 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 40 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 647 not found
[WARNING] [2025-04-25 16:32:05,534:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 690 not found
[WARNING] [2025-04-25 16:32:05,535:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 129 not found
[WARNING] [2025-04-25 16:32:05,535:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 347 not found
[WARNING] [2025-04-25 16:32:05,535:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 434 not found
[WARNING] [2025-04-25 16:32:05,535:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 264 not found
[WARNING] [2025-04-25 16:32:05,535:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 257 not found
[WARNING] [2025-04-25 16:32:05,535:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 532 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 701 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 329 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 590 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 150 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 670 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 293 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 75 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 399 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 154 not found
[WARNING] [2025-04-25 16:32:05,536:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 332 not found
[WARNING] [2025-04-25 16:32:05,537:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 61 not found
[WARNING] [2025-04-25 16:32:05,537:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 460 not found
[WARNING] [2025-04-25 16:32:05,537:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 230 not found
[WARNING] [2025-04-25 16:32:05,537:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 211 not found
[WARNING] [2025-04-25 16:32:05,537:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 358 not found
[WARNING] [2025-04-25 16:32:05,537:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 345 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 17 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 124 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 298 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 617 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 32 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 291 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 445 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 352 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 683 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 270 not found
[WARNING] [2025-04-25 16:32:05,538:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 546 not found
[WARNING] [2025-04-25 16:32:05,539:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 571 not found
[WARNING] [2025-04-25 16:32:05,539:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 183 not found
[WARNING] [2025-04-25 16:32:05,539:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 112 not found
[WARNING] [2025-04-25 16:32:05,539:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 494 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 375 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 131 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 134 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 171 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 121 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 403 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 528 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 58 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 480 not found
[WARNING] [2025-04-25 16:32:05,540:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 243 not found
[WARNING] [2025-04-25 16:32:05,541:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 25 not found
[WARNING] [2025-04-25 16:32:05,542:Client-AutoMLSMBO(1)::cb431fdc-21f2-11f0-9370-423b658c063e] Configuration 452 not found
[WARNING] [2025-04-25 16:32:07,389:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:07,500:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:07,584:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:07,640:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:09,826:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:09,879:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:11,434:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:13,150:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:15,054:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:16,959:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:18,816:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:20,775:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:23,468:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:23,549:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:23,606:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:25,365:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:27,349:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:29,056:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:30,771:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:32,194:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:33,546:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:35,039:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:36,574:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:38,012:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:39,452:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:41,081:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:42,549:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:32:43,905:Client-EnsembleBuilder] No runs were available to build an ensemble from

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=120,
                      time_left_for_this_task=60)

Ne fournis pas de résultats pertinant, potentielement par manque de temps de calcul (30min avait été testé)

In [12]:
cls.leaderboard()

          rank  ensemble_weight  type  cost duration
model_id
1            1              1.0  <NA>  <NA>     <NA>

Ici, nous voyons que le modèle n'est même pas arriver à faire une ligne (facteur séparateur)

In [13]:
predictions_Hunt = list(cls.predict(variables_testQ))

précision :

In [14]:
print("Accuracy score:", sklearn.metrics.accuracy_score(np.array(classes_testQ), predictions_Hunt))

Accuracy score: 0.14220292815798433

table des stats

In [15]:
print( sklearn.metrics.classification_report(classes_testQ, predictions_Hunt) )

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          NA       0.14      1.00      0.25     75177
          No       0.00      0.00      0.00     75219
         Yes       0.00      0.00      0.00    378264

    accuracy                           0.14    528660
   macro avg       0.05      0.33      0.08    528660
weighted avg       0.02      0.14      0.04    528660

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

décevant : on a un précision catastrophique.

Nous allons regarder la matrice de confusion pour potentiellement observer quel groupe est le mieu prédit

In [16]:
np.round( confusion_matrix(classes_testQ, predictions_Hunt), 3)

array([[ 75177,      0,      0],
       [ 75219,      0,      0],
       [378264,      0,      0]])

Le problème est clair : on prédit tout en une classe

## Tentative avec du quantitatif

### Ouverture du csv

In [17]:
dfQuanti = pd.read_csv('data/OutCatdataQuantiNormZ.csv', na_filter= False)
dfQuanti = dfQuanti.drop("Unnamed: 0", axis= 1)

/tmp/ipykernel_37744/2793842605.py:1: DtypeWarning: Columns (6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  dfQuanti = pd.read_csv('data/OutCatdataQuantiNormZ.csv', na_filter= False)

### Suppression des lignes ayant des Na

In [18]:
dfQuanti = dfQuanti[~np.any(dfQuanti == "NA",axis=1)]

### Création des sous jeux de données de test et d'entrainement

In [19]:
x = dfQuanti.drop('Hunt', axis=1).to_numpy().astype(np.float64)
y = dfQuanti.Hunt.astype(object)

y[y ==	-2.16472428387967] = "Na"
y[y == 	-0.78922734140023] = "No"
y[y ==   0.586269601079213]  = "Yes"

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size = 0.5, random_state=0)

### Établissement d'un modèle

In [20]:
cls_hunt = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=900, 
    per_run_time_limit=100, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

Ajustment du modèle a notre jeu de données

In [21]:
cls_hunt.fit(x_train, y_train, dataset_name='Cat Data')

[WARNING] [2025-04-25 16:33:02,764:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-25 16:33:02,764:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-25 16:33:02,764:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-25 16:33:02,764:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-25 16:33:02,764:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-25 16:33:02,764:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-25 16:33:02,765:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-25 16:33:02,765:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-25 16:33:02,765:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-25 16:33:02,765:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-25 16:33:02,766:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-25 16:33:02,767:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-25 16:33:02,767:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-25 16:33:02,767:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-25 16:33:02,767:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-25 16:33:02,767:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-25 16:33:02,767:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-25 16:33:02,768:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-25 16:33:02,768:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-25 16:33:02,769:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-25 16:33:02,770:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-25 16:33:02,771:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-25 16:33:02,771:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-25 16:33:02,772:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-25 16:33:02,772:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-25 16:33:02,772:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-25 16:33:02,772:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-25 16:33:02,773:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-25 16:33:02,774:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-25 16:33:02,775:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-25 16:33:02,776:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-25 16:33:02,776:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-25 16:33:02,776:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-25 16:33:02,776:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-25 16:33:02,776:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-25 16:33:02,776:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-25 16:33:02,777:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-25 16:33:02,778:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-25 16:33:02,779:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-25 16:33:02,779:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-25 16:33:02,779:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-25 16:34:43,174:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:46,598:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:49,914:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:49,956:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:53,910:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:53,962:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:53,998:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:34:57,354:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:05,488:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:25,494:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:14,932:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:17,892:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:38,728:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:41,548:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:53,552:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:56,155:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:59,771:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:35:59,827:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:03,804:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:10,872:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:11,062:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:45,656:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:35,666:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:38,072:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:38,122:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:38,174:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:05,695:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:48,158:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:50,978:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:51,035:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:53,941:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,020:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,104:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,227:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,293:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,490:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,562:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,755:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:36:58,849:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:04,288:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:04,362:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:08,985:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:09,102:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:13,641:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:16,629:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:16,695:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:21,327:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:21,559:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:25,564:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:25,668:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:37,841:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:41,666:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:51,751:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:51,826:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:56,917:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:37:56,995:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:07,261:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:07,477:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:19,964:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:20,104:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:29,133:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:33,575:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:33,651:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:37,347:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:38:37,447:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=100,
                      time_left_for_this_task=900)

### Affichage des résultats

### Affichage des facteurs

In [22]:
cls_hunt.leaderboard()

          rank  ensemble_weight                 type      cost   duration
model_id
5            1             0.02  k_nearest_neighbors  0.000000  28.148295
36          14             0.02                  mlp  0.000000  67.612292
51          15             0.02  k_nearest_neighbors  0.000000  58.813273
62          16             0.02  k_nearest_neighbors  0.000000  21.114990
82          13             0.06  k_nearest_neighbors  0.000000  24.348719
85          11             0.04  k_nearest_neighbors  0.000000  27.978028
111         10             0.06  k_nearest_neighbors  0.000000  21.953785
113          9             0.02  k_nearest_neighbors  0.000000  35.409569
117          8             0.02  k_nearest_neighbors  0.000000  38.517160
124          7             0.10  k_nearest_neighbors  0.000000  16.993834
140          6             0.08  k_nearest_neighbors  0.000000   1.308189
141          5             0.02  k_nearest_neighbors  0.000000   0.389446
143          4             0.02  k_nearest_neighbors  0.000000  34.556961
154          3             0.02  k_nearest_neighbors  0.000000  26.924861
164          2             0.04  k_nearest_neighbors  0.000000  25.654230
181         12             0.02  k_nearest_neighbors  0.000000  13.867680
57          18             0.02  k_nearest_neighbors  0.000006  22.571181
75          20             0.02  k_nearest_neighbors  0.000006  62.556728
79          21             0.04  k_nearest_neighbors  0.000006  35.851392
86          24             0.02  k_nearest_neighbors  0.000006  51.517579
87          19             0.04  k_nearest_neighbors  0.000006  21.451643
98          22             0.02  k_nearest_neighbors  0.000006  31.316119
156         17             0.04  k_nearest_neighbors  0.000006  64.243014
166         23             0.02  k_nearest_neighbors  0.000006   2.764835
43          25             0.02  k_nearest_neighbors  0.000035  28.954514
139         26             0.06  k_nearest_neighbors  0.000052   6.436562
11          27             0.06                  lda  0.148828  37.248400
84          28             0.02          gaussian_nb  0.149330  11.893960
70          30             0.02                  lda  0.150713  37.863071
146         29             0.02                  lda  0.150713  45.342991

### Stockage des prédictions

In [23]:
predictions_Hunt = list(cls_hunt.predict(x_test))

### Affichage des stats

In [24]:
print( sklearn.metrics.classification_report(y_test, predictions_Hunt) )

              precision    recall  f1-score   support

          Na       1.00      1.00      1.00     72285
          No       1.00      1.00      1.00     75535
         Yes       1.00      1.00      1.00    377823

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

### Affichage de la matrice de confusion

In [25]:
np.round( confusion_matrix(y_test, predictions_Hunt), 3)

array([[ 72285,      0,      0],
       [     0,  75535,      0],
       [     0,      0, 377823]])

# Prédiction du nombre de proie par chats

## création des 2 matrices

In [26]:
x2 = dfQuanti.drop('N.pray', axis=1).to_numpy().astype(np.float64)
y2 = dfQuanti['N.pray'].astype(object)

### To-do ya des strings dans dfQuanti['N.pray'] 

on les supprimes en copiant dans une liste temp que les float

In [27]:
out = []
for i in y2 : 
    if type(i) == float:
        out.append(i)
    elif type(i) == str :
        out.append(float(i))

y2 = pd.Series(out).astype(object)

### transformer les nombre de poids normalisé en leur valeur d'origine

génération d'un dico de traduction

In [28]:
dictUnfoctor = {}

fooKeys = np.unique(y2)
fooVals = np.unique(df['N.pray'].astype(object))

In [29]:
for i in range(len(fooKeys)):
    dictUnfoctor[fooKeys[i]] = fooVals[i]

application du dico

In [30]:
for pos in range(len(y2)) : 
    y2[pos] = str(dictUnfoctor[y2[pos]])

## On a fini le formatage, c'est l'heure de faire le jeu de test et le jeu d'entrainement

In [31]:
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2,
                                                    test_size = 0.5, random_state=0)

## Configuration du modèle

In [32]:
cls_Npray = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=800, 
    per_run_time_limit=160, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

### Affinage du modèle

In [33]:
cls_Npray.fit(x2_train, y2_train, dataset_name='Cat Data')

[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-25 16:51:08,234:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-25 16:51:08,235:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-25 16:51:08,236:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-25 16:51:08,237:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-25 16:51:08,238:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-25 16:51:08,238:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-25 16:51:08,238:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-25 16:51:08,238:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-25 16:51:08,238:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-25 16:51:08,238:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-25 16:51:08,239:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-25 16:51:08,240:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-25 16:51:08,240:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-25 16:51:08,240:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-25 16:51:08,240:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-25 16:51:08,240:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-25 16:51:08,240:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-25 16:51:08,241:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-25 16:51:08,241:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-25 16:51:08,241:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-25 16:51:08,241:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-25 16:51:08,241:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-25 16:51:08,241:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-25 16:51:08,242:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-25 16:51:08,242:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-25 16:51:08,242:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-25 16:51:08,242:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-25 16:51:08,242:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-25 16:51:08,242:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-25 16:51:08,243:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-25 16:51:08,243:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-25 16:51:08,244:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-25 16:51:08,245:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-25 16:51:08,245:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-25 16:51:08,245:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-25 16:51:08,245:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-25 16:51:08,246:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-25 16:51:08,246:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-25 16:51:08,246:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-25 16:51:32,255:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 16:53:49,151:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:13,355:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:17,538:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:17,637:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:09,520:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:09,583:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:09,664:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:12,755:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:12,802:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:16,468:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:21,102:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:23,904:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:23,951:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:54:42,241:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:55:09,736:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:55:16,498:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:55:20,686:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:55:14,111:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:55:14,153:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:27,162:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:31,716:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:31,786:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:35,720:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:40,126:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:40,201:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:40,267:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:46,906:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:47,102:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:52,086:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:52,199:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:52,325:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:52,492:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:52,632:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:53,907:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:58,685:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:59,202:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:56:59,266:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:05,034:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:05,067:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:07,139:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:10,479:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:10,563:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:14,824:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:15,066:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:19,040:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:19,110:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:22,528:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:25,348:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:26,916:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:27,031:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:41,138:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:46,974:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:57:50,053:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:07,019:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:13,108:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:18,339:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:23,152:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:26,789:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:32,325:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:32,517:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:32,608:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:38,560:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:44,082:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 16:59:44,195:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=160,
                      time_left_for_this_task=800)

## Affichage des résultats

### Affichage des facteurs

In [34]:
cls_Npray.leaderboard()

          rank  ensemble_weight                 type      cost    duration
model_id
6            1             0.10  k_nearest_neighbors  0.000000   21.694445
17           2             0.06  k_nearest_neighbors  0.000000   15.760657
48           5             0.06  k_nearest_neighbors  0.000000   59.319450
55           4             0.06  k_nearest_neighbors  0.000000   17.356538
71           3             0.06  k_nearest_neighbors  0.000000   87.129201
81           6             0.04  k_nearest_neighbors  0.000006   53.989300
70           7             0.04  k_nearest_neighbors  0.000184   65.381284
40           8             0.02  k_nearest_neighbors  0.000259  107.525117
24           9             0.08  k_nearest_neighbors  0.001897   87.548279
50          10             0.02  k_nearest_neighbors  0.049532   15.044491
49          11             0.08                  lda  0.403437   26.593449
31          12             0.08                  lda  0.436557   12.074833
82          13             0.04                  lda  0.455483   14.822052
60          14             0.02                  lda  0.511553   11.791441
41          15             0.06                  lda  0.520166    5.813848
35          16             0.02          gaussian_nb  0.562901    5.940706
36          17             0.02          gaussian_nb  0.576288   21.107393
51          18             0.02                  lda  0.583108  134.684551
57          19             0.06          gaussian_nb  0.618285    6.165270
85          20             0.06          gaussian_nb  0.632824    9.528580

On voit que la méthode avec les modeles les plus significatf sont : Ida et gaussian_nb

### Stockage des prédictions

In [35]:
predictions_Npray = list(cls_Npray.predict(x2_test))

### Affichage des stats

In [36]:
print( sklearn.metrics.classification_report(y2_test, predictions_Npray) )

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00    163262
           0       1.00      1.00      1.00    106831
           1       1.00      1.00      1.00     53779
          10       1.00      1.00      1.00     16599
          11       1.00      1.00      1.00      2699
          13       1.00      1.00      1.00      1214
          15       1.00      1.00      1.00      3493
          16       1.00      1.00      1.00       808
          17       1.00      1.00      1.00       561
          19       1.00      1.00      1.00      7307
           2       1.00      1.00      1.00     53685
           3       1.00      1.00      1.00     28708
           4       1.00      1.00      1.00     41843
           5       1.00      1.00      1.00     19360
           6       1.00      1.00      1.00     11099
           7       1.00      1.00      1.00      3248
           8       1.00      1.00      1.00      8978
           9       1.00      1.00      1.00      2169

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

1 de précision pour chaque classes

### Affichage de la matrice de confusion

In [37]:
np.round( confusion_matrix(y2_test, predictions_Npray), 3)

array([[163262,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0, 106831,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,  53779,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,  16599,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,   2699,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,   1214,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,   3493,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,    808,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
           561,      0,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,   7307,      0,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,  53685,      0,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,  28708,      0,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,  41843,      0,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,  19360,      0,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,  11099,      0,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,   3248,
             0,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
          8978,      0],
       [     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,   2169]])

problême trop fort : on a une matrice de test diagonalle : aucune mauvaise prédiction, 100% de vrai

donc possibilité de réduire le temps de calcul pour l'entrainement

# Dernière prédiction le temps passé à l'intérieur

## création des 2 matrices

In [96]:
x3 = dfQuanti.drop('Hrs.indors', axis=1).to_numpy().astype(np.float64)
y3 = dfQuanti['Hrs.indors'].astype(object)

on les supprimes en copiant dans une liste temp que les float

In [97]:
out = []
for i in y3 : 
    if type(i) == float:
        out.append((i))
    elif type(i) == str :
        out.append(float(i))

y3 = pd.Series(out).astype(object)

### transformer les nombre de poids normalisé en leur valeur d'origine

génération d'un dico de traduction

In [98]:
dictUnfoctor = {}

fooKeys = np.unique(y3)
fooVals = (df['Hrs.indors'].astype(object))

restriction des données sous forme de string

In [101]:
out = []
for i in fooVals : 
    if type(i) == float:
        out.append(str(i))
    elif type(i) != float :
        out.append((i))

fooVals = pd.unique(out).astype(object)

création dico de traduction

In [102]:
for i in range(len(fooKeys)):
    dictUnfoctor[fooKeys[i]] = fooVals[i]

application du dico

In [103]:
for pos in range(len(y3)) : 
    y3[pos] = str(dictUnfoctor[y3[pos]])

## On a fini le formatage, c'est l'heure de faire le jeu de test et le jeu d'entrainement

In [104]:
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3,
                                                    test_size = 0.5, random_state=0)

## Configuration du modèle

In [ ]:
cls_HrsOut = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=600, 
    per_run_time_limit=160, 
    n_jobs=16,
    include = {"classifier":["random_forest",
                                "lda",
                                "mlp", # multilayer perceptron
                                "gaussian_nb", #  Naive Bayes
                                "k_nearest_neighbors"]},
    memory_limit=24576)

### Affinage du modèle

In [106]:
cls_HrsOut.fit(x3_train, y3_train, dataset_name='Cat Data')

[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 628 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 288 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 298 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 647 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 17 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 434 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 173 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 124 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 494 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 277 not found
[WARNING] [2025-04-25 17:57:03,627:Client-AutoMLSMBO(1)::Cat Data] Configuration 683 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 352 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 129 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 571 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 171 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 412 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 595 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 88 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 134 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 528 not found
[WARNING] [2025-04-25 17:57:03,628:Client-AutoMLSMBO(1)::Cat Data] Configuration 403 not found
[WARNING] [2025-04-25 17:57:03,629:Client-AutoMLSMBO(1)::Cat Data] Configuration 121 not found
[WARNING] [2025-04-25 17:57:03,629:Client-AutoMLSMBO(1)::Cat Data] Configuration 445 not found
[WARNING] [2025-04-25 17:57:03,630:Client-AutoMLSMBO(1)::Cat Data] Configuration 608 not found
[WARNING] [2025-04-25 17:57:03,630:Client-AutoMLSMBO(1)::Cat Data] Configuration 112 not found
[WARNING] [2025-04-25 17:57:03,630:Client-AutoMLSMBO(1)::Cat Data] Configuration 37 not found
[WARNING] [2025-04-25 17:57:03,630:Client-AutoMLSMBO(1)::Cat Data] Configuration 617 not found
[WARNING] [2025-04-25 17:57:03,630:Client-AutoMLSMBO(1)::Cat Data] Configuration 14 not found
[WARNING] [2025-04-25 17:57:03,631:Client-AutoMLSMBO(1)::Cat Data] Configuration 69 not found
[WARNING] [2025-04-25 17:57:03,631:Client-AutoMLSMBO(1)::Cat Data] Configuration 605 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 521 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 243 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 518 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 414 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 426 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 378 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 367 not found
[WARNING] [2025-04-25 17:57:03,632:Client-AutoMLSMBO(1)::Cat Data] Configuration 480 not found
[WARNING] [2025-04-25 17:57:03,633:Client-AutoMLSMBO(1)::Cat Data] Configuration 108 not found
[WARNING] [2025-04-25 17:57:03,633:Client-AutoMLSMBO(1)::Cat Data] Configuration 204 not found
[WARNING] [2025-04-25 17:57:03,633:Client-AutoMLSMBO(1)::Cat Data] Configuration 624 not found
[WARNING] [2025-04-25 17:57:03,633:Client-AutoMLSMBO(1)::Cat Data] Configuration 659 not found
[WARNING] [2025-04-25 17:57:03,634:Client-AutoMLSMBO(1)::Cat Data] Configuration 506 not found
[WARNING] [2025-04-25 17:57:03,634:Client-AutoMLSMBO(1)::Cat Data] Configuration 206 not found
[WARNING] [2025-04-25 17:57:03,635:Client-AutoMLSMBO(1)::Cat Data] Configuration 327 not found
[WARNING] [2025-04-25 17:57:03,635:Client-AutoMLSMBO(1)::Cat Data] Configuration 532 not found
[WARNING] [2025-04-25 17:57:03,635:Client-AutoMLSMBO(1)::Cat Data] Configuration 347 not found
[WARNING] [2025-04-25 17:57:03,635:Client-AutoMLSMBO(1)::Cat Data] Configuration 262 not found
[WARNING] [2025-04-25 17:57:03,635:Client-AutoMLSMBO(1)::Cat Data] Configuration 386 not found
[WARNING] [2025-04-25 17:57:03,635:Client-AutoMLSMBO(1)::Cat Data] Configuration 579 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 238 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 657 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 232 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 257 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 329 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 590 not found
[WARNING] [2025-04-25 17:57:03,636:Client-AutoMLSMBO(1)::Cat Data] Configuration 444 not found
[WARNING] [2025-04-25 17:57:03,637:Client-AutoMLSMBO(1)::Cat Data] Configuration 492 not found
[WARNING] [2025-04-25 17:57:03,637:Client-AutoMLSMBO(1)::Cat Data] Configuration 702 not found
[WARNING] [2025-04-25 17:57:03,637:Client-AutoMLSMBO(1)::Cat Data] Configuration 61 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 332 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 75 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 211 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 694 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 358 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 399 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 460 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 524 not found
[WARNING] [2025-04-25 17:57:03,638:Client-AutoMLSMBO(1)::Cat Data] Configuration 345 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 668 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 7 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 230 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 467 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 40 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 631 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 563 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 690 not found
[WARNING] [2025-04-25 17:57:03,639:Client-AutoMLSMBO(1)::Cat Data] Configuration 32 not found
[WARNING] [2025-04-25 17:57:03,640:Client-AutoMLSMBO(1)::Cat Data] Configuration 574 not found
[WARNING] [2025-04-25 17:57:03,640:Client-AutoMLSMBO(1)::Cat Data] Configuration 264 not found
[WARNING] [2025-04-25 17:57:03,641:Client-AutoMLSMBO(1)::Cat Data] Configuration 546 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 430 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 670 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 701 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 302 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 293 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 154 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 131 not found
[WARNING] [2025-04-25 17:57:03,642:Client-AutoMLSMBO(1)::Cat Data] Configuration 291 not found
[WARNING] [2025-04-25 17:57:03,643:Client-AutoMLSMBO(1)::Cat Data] Configuration 270 not found
[WARNING] [2025-04-25 17:57:03,643:Client-AutoMLSMBO(1)::Cat Data] Configuration 183 not found
[WARNING] [2025-04-25 17:57:03,643:Client-AutoMLSMBO(1)::Cat Data] Configuration 452 not found
[WARNING] [2025-04-25 17:57:03,643:Client-AutoMLSMBO(1)::Cat Data] Configuration 58 not found
[WARNING] [2025-04-25 17:57:03,643:Client-AutoMLSMBO(1)::Cat Data] Configuration 375 not found
[WARNING] [2025-04-25 17:57:03,644:Client-AutoMLSMBO(1)::Cat Data] Configuration 102 not found
[WARNING] [2025-04-25 17:57:03,644:Client-AutoMLSMBO(1)::Cat Data] Configuration 25 not found
[WARNING] [2025-04-25 17:57:03,645:Client-AutoMLSMBO(1)::Cat Data] Configuration 150 not found
[WARNING] [2025-04-25 17:57:07,281:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2025-04-25 17:59:45,136:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:48,257:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:48,297:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:51,074:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:51,115:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:51,173:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:51,246:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:51,336:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 17:59:54,662:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:00:00,494:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:00:00,662:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:00:05,858:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:00:12,111:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:00:15,582:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:00:19,397:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:03,241:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:08,725:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:18,091:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:03,197:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:18,274:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:18,318:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:22,731:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:22,812:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:47,447:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:01:52,058:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:26,144:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:26,314:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:28,381:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:30,705:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:54,905:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:34,646:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:34,710:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:37,840:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:37,903:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:37,985:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:38,096:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:38,183:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:39,097:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:44,869:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:45,096:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:47,911:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:52,194:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:02:52,293:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:00,628:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:02,967:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:06,371:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:08,723:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:10,117:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:13,667:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:15,461:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:15,631:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:32,964:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:39,085:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:03:45,041:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:04:45,770:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:04:50,770:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:04:55,060:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:04:58,959:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:05:06,769:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:05:06,909:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:05:07,453:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:05:11,031:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:05:14,392:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2025-04-25 18:05:14,476:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      include={'classifier': ['random_forest', 'lda', 'mlp',
                                              'gaussian_nb',
                                              'k_nearest_neighbors']},
                      memory_limit=24576, n_jobs=16, per_run_time_limit=160,
                      time_left_for_this_task=800)

## Affichage des résultats

### Affichage des facteurs

In [107]:
cls_HrsOut.leaderboard()

          rank  ensemble_weight                 type      cost    duration
model_id
35           3             0.02  k_nearest_neighbors  0.000000   51.010965
61           4             0.10  k_nearest_neighbors  0.000000    6.959752
81           2             0.02  k_nearest_neighbors  0.000000   28.192889
96           1             0.02  k_nearest_neighbors  0.000000   22.981563
5            8             0.02  k_nearest_neighbors  0.000006   22.130774
69           7             0.04  k_nearest_neighbors  0.000006   14.471778
80           6             0.02  k_nearest_neighbors  0.000006   23.909456
83           5             0.08  k_nearest_neighbors  0.000006   24.052580
66          10             0.02  k_nearest_neighbors  0.000012   19.984966
86          11             0.08  k_nearest_neighbors  0.000012   48.398042
88           9             0.02  k_nearest_neighbors  0.000012   38.398861
77          12             0.02  k_nearest_neighbors  0.000017    8.702924
93          13             0.02  k_nearest_neighbors  0.000023   25.853725
59          14             0.02  k_nearest_neighbors  0.000035   99.357352
68          15             0.04  k_nearest_neighbors  0.000040   64.349353
45          16             0.02  k_nearest_neighbors  0.000300   20.417351
38          17             0.02  k_nearest_neighbors  0.000784  117.998882
73          18             0.02  k_nearest_neighbors  0.231163   37.969112
75          19             0.06          gaussian_nb  0.593582    2.244164
90          20             0.02                  lda  0.721530   10.147581
67          21             0.04                  lda  0.727381   60.724820
94          22             0.04          gaussian_nb  0.743189   -4.189575
87          23             0.08                  lda  0.771114   34.749118
46          24             0.02                  lda  0.776009    4.391398
32          25             0.04          gaussian_nb  0.779496   91.337958
34          27             0.02                  mlp  0.874635  126.894241
39          28             0.02                  mlp  0.874635   37.530009
40          26             0.02                  mlp  0.874635   82.254068
31          29             0.04                  mlp  0.961502   86.937343

méthode donnant le plus de poids : k_nearest_neighbors

### Stockage des prédictions

In [109]:
predictions_HrsOut = list(cls_HrsOut.predict(x3_test))

plutot "long" car on test +500000 lignes

### Affichage des stats

In [110]:
print( sklearn.metrics.classification_report(y3_test, predictions_HrsOut) )

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6519
           1       1.00      1.00      1.00     65575
          10       1.00      1.00      1.00     41745
          12       1.00      1.00      1.00     43796
          14       1.00      1.00      1.00     13201
          15       1.00      1.00      1.00     36938
          16       1.00      1.00      1.00     16434
          18       1.00      1.00      1.00     53462
           2       1.00      1.00      1.00     52736
          20       1.00      1.00      1.00     12525
          23       1.00      1.00      1.00      7306
           3       1.00      1.00      1.00     20568
           4       1.00      1.00      1.00     10083
           5       1.00      1.00      1.00     23066
           6       1.00      1.00      1.00     13023
           7       1.00      1.00      1.00     11637
           8       1.00      1.00      1.00     29453
           9       1.00      1.00      1.00     64770
          NA       1.00      1.00      1.00      2806

    accuracy                           1.00    525643
   macro avg       1.00      1.00      1.00    525643
weighted avg       1.00      1.00      1.00    525643

### Affichage de la matrice de confusion

In [111]:
np.round( confusion_matrix(y3_test, predictions_HrsOut), 3)

array([[ 6519,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 65575,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0, 41745,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0, 43796,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0, 13201,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0, 36937,     0,     0,     0,
            0,     0,     0,     0,     1,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0, 16434,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0, 53462,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0, 52736,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
        12525,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,  7306,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0, 20568,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 10083,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0, 23066,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0, 13023,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0, 11637,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0, 29453,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0, 64770,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
         2806]])